### ISSUE TITLE
Feature Request: Highlighting of errors in the corresponding file

### ISSUE THREAD

**Issue by cwinkler89** [CoatiSoftware/SourcetrailBugTracker#110]
When I open a file that contains an error the line responsible for the error is no longer highlighted as it is in the overview.
In addition to highlighting a shortcut/menu entry/button would be nice that allows jumping to the next/previous error.

**Comment by egraether** [comment]
Was fixed before 2017.2.0
Errors messages are now also shown in errors table within status view.
Reference navigation on top of code view can be used to switch errors.
