### ISSUE TITLE
Bookmarks, Tags and Notes for symbols

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#138]

**Comment by egraether** [comment]
+1 by feedback mail

**Comment by egraether** [comment]
+1 by feedback mail

**Comment by egraether** [comment]
Allow symbols to get bookmarked.
Bookmarks can contain comments that should be searchable.
Bookmarks can get tagged for grouping.

**Comment by egraether** [comment]
+1 by feedback mail

**Comment by egraether** [comment]
+1 by mail

**Comment by mlangkabel** [comment]
implemented with Sourcetrail 0.11.92
