### ISSUE TITLE
VS-Plugin freezes Visual Studio UI after installation or during use

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#164]
Sometimes accompanied by error dialog that unfreezes the UI afterwards:
![image006](https://cloud.githubusercontent.com/assets/201867/17736081/0730229c-6486-11e6-81b1-bab916d8120b.jpg)

**Comment by mlangkabel** [comment]
Closing this issue now because it's probably already resolved with the release version of the Visual Studio extension. Please post new issues regarding the Visual Studio extension to the [Sourcetrail Extension issue tracker](https://github.com/CoatiSoftware/vs-sourcetrail/issues).
