### ISSUE TITLE
Error message from VS-Plugin when Coati is not running

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#165]
Set Token option should not be clickable when there is no connection.

![image008](https://cloud.githubusercontent.com/assets/201867/17736246/fed80e56-6486-11e6-8660-f2996c4a8700.jpg)

**Comment by mlangkabel** [comment]
From October 2016 on these exceptions are handled inside the Visual Studio extension, logging any failure so the user knows what's going on.
