### ISSUE TITLE
Keep bundle name visible after bundles in the overview were clicked

### ISSUE THREAD

**Issue by Mike4Online** [CoatiSoftware/SourcetrailBugTracker#171]
If I click Functions from the Overview screen, the "Functions" item disappears and I then see a list of all the functions.  But it would be better if the item "Functions" remained on the screen, perhaps **in bold**, so I would have a visual reminder that the items I was looking at were Functions.  The same applies when clicking any object type from the Overview, such as enums.

I am using Coati 0.7.0.22

**Comment by egraether** [comment]
Implemented with 2018.1.95
