### ISSUE TITLE
Re-Indexing in the background

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#175]
Coati should stay usable while re-indexing the current project.

**Comment by miki151** [comment]
You could also add a way to trigger indexing from command line, which could be hooked up to 'git commit' or something.

This way when I open Coati, the index would be already fresh. My biggest problem is that when I need to look something up, I open Coati, but it's out of date, and by the time indexing finishes, I've found the info elsewhere.

**Comment by egraether** [comment]
+1 via mail

**Comment by egraether** [comment]
+1 via mail

**Comment by egraether** [comment]
Intermediate .srctrldb files should include uuid of indexing instance to also fix #158

**Comment by egraether** [comment]
Implemented with 2018.2.92
