### ISSUE TITLE
Coati handle "unknown" compilation options poorly

### ISSUE THREAD

**Issue by ffuugoo** [CoatiSoftware/SourcetrailBugTracker#188]
I use Coati to analyse camcoder-firmware code base. It use GCC 4.7 for compilation and, obviously, it use some pretty obscure compilation options. 

The issue is that if you feed Coati a compilation database which contains some of this "obscure" options it will just skip all such files silently (well, almost, it drops a lot of error messages into the terminal/log).

Terminal:
![coati-compilation-options-bug-1](https://cloud.githubusercontent.com/assets/2725918/18339664/355f8396-75e4-11e6-83d5-d6e499467850.png)

Coati:
![coati-compilation-options-bug-2](https://cloud.githubusercontent.com/assets/2725918/18339679/4db78ec0-75e4-11e6-914d-9a3a862afcb3.png)

**Comment by mlangkabel** [comment]
Thanks for reporting this one. I just did some research and it appears that gcc has a lot of flags that the Clang compiler (used by Coati) does not recognize. Luckily the Clang developers are aware of this issue and introduced a flag for this:

`-Wno-error=unused-command-line-argument`

So just try to add this flag (including the "-") to the Compiler Flags list in your Edit Project window (advanced settings) and let us know how this works for you.

**Comment by titovroman** [comment]
Unfortunately, it does not work. I've tried adding this option to existing Coati-project and creating new one from scratch. 

I've also tried adding `-Wno-error=unused-command-line-argument-hard-error-in-future` ([found here](https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress/))  and `-Qunused-arguments` ([found here](https://stackoverflow.com/questions/21617158/how-to-silence-unused-command-line-argument-error-with-clang-without-disabling-i)). Without any luck as well.

**Comment by mlangkabel** [comment]
Thank you for testing these options! I guess now it's time for us to try reproducing that issue and come up with a fix ;) Do you already have some command line options that you know will make the indexer fail?

**Comment by titovroman** [comment]
Well, `-march=armv7-a`, `-mno-thumb-interwork`, `-fconserve-stack`, and `-fno-var-tracking-assignments`? (They are from the screenshot). :D

Actually, I'm _**almost**_ sure everything will do, like `-this-option-almost-certainly-does-not-even-exist`.

**Comment by mlangkabel** [comment]
Ok, I have tested this a lot by now and it doesn't seem that all these `unknown argument` errors are the problem.

The real issue seems to be the `unknown target CPU 'armv7-a'` error. To solve this issue please try to override the architecture setting specified by your compile command: Just add the following flag to your project settings.

`-march=i486`
