### ISSUE TITLE
Change visualisation of structs/enums/unions declared using typedef

### ISSUE THREAD

**Issue by ffuugoo** [CoatiSoftware/SourcetrailBugTracker#189]
I have a mixed C/C++ code base, and so the "typedef - anonymous enum/union/struct - typename" declarations used extensively. (Is there special name for such declarations?)

However, Coati visualise such types in the form that is a bit annoying to use:
![screenshot from 2016-09-08 17-23-56](https://cloud.githubusercontent.com/assets/2725918/18340780/3bf2d84c-75ea-11e6-8063-e1c6ad609020.png)
![screenshot from 2016-09-08 17-24-05](https://cloud.githubusercontent.com/assets/2725918/18340781/3bf50536-75ea-11e6-9aec-11f5eb04f124.png)

I think it would be nice to rework this aspect so that the "anonymous whatever" node could be excluded completely.

**Comment by mlangkabel** [comment]
Hi @titovroman. Thanks for telling us! That should be possible.

**Comment by kvakvs** [comment]
Is this still being worked on?
In a C project with abundance of such `typedef struct { ... } TypeName;` they all become anonymous structs used by a single `TypeName`, not comfortable at all.

**Comment by mlangkabel** [comment]
@kvakvs: Absolutely! We are planning to make this an optional feature that is enabled by default. I hope I'll get this done soon :)

**Comment by mlangkabel** [comment]
Implemented with Sourcetrail version 2017.2.34 (actually this feature is pretty cool, thanks again for requesting it!)
