### ISSUE TITLE
Extend tooltips to be interactive and show type and signature

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#195]
Tooltips should show:
* symbol type
* symbol name
* data type for variables, signatures for functions (with types clickable)
* show if un-indexed or implicit
* (show reference count)

**Comment by egraether** [comment]
Merged into #83

**Comment by egraether** [comment]
also add parameters and return types for functions

+1 by mail

**Comment by mlangkabel** [comment]
Hovering a function or a method already displays the full signature. Am I missing something?

**Comment by egraether** [comment]
It should be interactive. I thought we have an open bug for that. I'm extending this one instead.

**Comment by mlangkabel** [comment]
So normal tooltips are not interactive enough? ;)
Seriously, what do you mean?

**Comment by egraether** [comment]
Yes, I'd like to click the stuff inside the tooltips.

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Implemented with 2017.2.48
