### ISSUE TITLE
[Feature] Value conversion hex <-> dec

### ISSUE THREAD

**Issue by mtowalski** [CoatiSoftware/SourcetrailBugTracker#206]
It would be nice if You guys could add value conversion when viewing the code. I mean between hex -> dec and dec -> hex.

I mean like this :
struct C {
char val[0xb2];
} test;

and if I right click on 0xb2 it would convert to decimal value = 178.

**Comment by mlangkabel** [comment]
Great idea! Maybe this conversion should be in an additional-infos-popup that shows up when hovering the hex value.

**Comment by mtowalski** [comment]
Sounds good!

**Comment by egraether** [comment]
Has not come up again in almost 3 years. Seems like a use-case not many developers have. Closing.
