### ISSUE TITLE
Show origin of parameters used in a function call

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#213]
```
... foo.c

FunctionX(a,b,c);
```

```
... foo.c
Void callsFunctionX(a){
    ...
    int b = 0;
    ...
    Void* c = Null;
    ...
    c = mallloc(256);
    ....
    FunctionX(a, b, c);
```

**Comment by mlangkabel** [comment]
How should the origibn be shown? Right now you can hover the arguments of a function call and every occurrence of the corresponding symbol will get a highlight.

**Comment by mlangkabel** [comment]
We re-discussed this issue and the proposal is: when clicking on a local variable (e.g. an argument of a function call) all occurrences should be visible. so the visible snippet scope should be expanded if required,

**Comment by egraether** [comment]
Original suggestion was tracking variables between functions if I remember correctly. But this is not something we are interested in, since it requires dynamic analysis to properly work.

Show origin of local symbol within scope more easily continued in #714
