### ISSUE TITLE
VS plugin not working with VS 2012 

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#229]
VS 2012 will not show solution explorer window, class view window and other windows. When going to Extensions and updates VS 2012 crashes

**Comment by wrongway88** [comment]
Unable to recreate the issue. I'll need some more information about the affected system, like OS and VS version (e.g. Professional, Community...). Also, was a project loaded? Or was even that not possible? Was this experienced with only a specific project?

**Comment by mlangkabel** [comment]
Version 1.0 of the Visual Studio extension is now available in the VS gallery. To update just click `Tools` -> `Extensions and Updates...`. Under the `Updates` section choose to update the `Sourcetrail Extension` entry.

Please check if the issue still exists.

**Comment by mlangkabel** [comment]
Closing this issue now because it's probably already resolved and we haven't received any further feedback. Please post new issues regarding the Visual Studio extension to the [Sourcetrail Extension issue tracker](https://github.com/CoatiSoftware/vs-sourcetrail/issues).
