### ISSUE TITLE
See all errors for one source file

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#246]
and errors in all included files too?

**Comment by TTimo** [comment]
For instance, I lookup a class and Coati does not give me the outline. Only seems to suggest it's a forward declaration that it never saw the definition for.

I pull up the source file for it's implementation. I assume Coati had a fatal error when processing this file, but I have no good way to narrow down the cause. The suggested workaround is to copy out a temp project that has only that source file for now.

**Comment by mlangkabel** [comment]
Hey @TTimo! That sounds like a great suggestion. 
@egraether: For that use case we'd also need to display the errors that occurred in all the files included by the source file, since they are also part of the compilation process for individual source file.

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Implemented with 2018.1.69

Added a "show errors" button to the file title bar of incomplete files, which when clicked shows all errors within the file and all included files.
