### ISSUE TITLE
Search for possible codepaths between function A and function B

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#249]
reported by mail

**Comment by jpenalbae** [comment]
I would break this into

- Search for possible codepaths between function A and function B

- Search recursively if any of the callees of the current function call to function X
   - This could be done by right clicking, show a context menu and then input the desired function to search for.
   - Being able to define a custom list per project for this would be also cool, so you could have a submenu in the context menu with the custom entries such as `pthread_mutex_lock()`/`pthread_mutex_unlock()`, `mutex_lock()`/`mutex_unlock()`, and avoid having to type them every time.

**Comment by wrongway88** [comment]
Thanks for your feedback @jpenalbae, we will look into this as soon as we can.

**Comment by jpenalbae** [comment]
I forgot to mention another possible subtask:

* Find all the possible paths to reach function X

On a normal program all the codepaths would obviously always begin with `main()`. But for libraries it would show which exported symbols make use of function X, and for kernels it would show which syscalls or ioctls make use of the function X.

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Added support for call graphs, inheritance trees and include trees using Sugiyama-style graph drawing with 0.11.98

Searching for specific code paths between functions is not possible yet.

**Comment by schmotzle** [comment]
+1

**Comment by egraether** [comment]
Suggestion from Slack channel:
Use `functionA` `->` `functionB` syntax in search field. Also add actions `path to here` and `path from here` to graph context menu, which can be used when displaying a depth graph.

**Comment by egraether** [comment]
+1 via mail
Also allow specifying classes and involve all their members in the path search.

**Comment by egraether** [comment]
Also filter by containing file or directory

**Comment by dwlsalmeida** [comment]
By the way: I feel that composing an overview of part of the code for coworkers is somewhat limiting. Users can hide nodes, which is great, but they cannot add them. I feel that maybe users should be able to add nodes to the graph window and they should automatically connect if they're related.

**Comment by egraether** [comment]
Implemented with 2019.3.16

New **Custom Trail** dialog is available in the top left of the graph view and allows to search for:
* paths between A & B
* all paths starting from A
* all paths ending in A

Available options:
* search depth: 1 - 50 + infinite
* layout: horizontal/vertical
* filter: by node/edge types

Filtering by containing file or directory is still missing. Opened as new feature request #712.
