### ISSUE TITLE
Better indication for failed/interrupted indexing upon reopening Coati

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/SourcetrailBugTracker#256]
Reported via Mail

original text:
"after the crash when coati was reopened all screens were empty because indexing was not done yet but there was no indicator for that, i opened the project explicitly again and then it asked me to index it which worked fine and was very quick"

**Comment by mlangkabel** [comment]
So Coati did not show the start screen (the one where you can choose to open a recent project) when restarting?

**Comment by iridic** [comment]
Yes, it didn't show up. 
Basically what happened is I had a fresh install, but the application crashed on start because java 6 was not found. When I started the app again after installing java 6, Coati opened without any welcome window, and all panels were empty.

**Comment by egraether** [comment]
Error handling during indexing has changed a lot with our last releases, so this is no longer up-to-date.
Closing now.
