### ISSUE TITLE
Graph should show difference between overloaded methods

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/SourcetrailBugTracker#259]
Reported via Mail

Original text:
"when there are several methods overloaded in the class then it would be nice to add the params or maybe the beginning of the params or the count or something… we use an eventbus architecture and have lots of “onEvent(EventClass event)” methods which look all the same in coati and you have to click through them to check them out"

**Comment by mlangkabel** [comment]
This is definitely an issue. Right now you can hover the nodes in the graph to see the full signature.

**Comment by egraether** [comment]
Implemented with 2018.2.97
Adding parameters to functions/method names when same name and within same parent or no parent.
