### ISSUE TITLE
vim plugin doesn't set cursor with :CoatiRefresh

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#263]
reported via mail

**Comment by mpbraendli** [comment]
Observed running both neovim 0.1.7 and vim 8.0 running on Arch Linux.

:CoatiActivateToken works, but :CoatiRefresh silently fails (i.e. no effect observed)

**Comment by mpbraendli** [comment]
Additional information:

As observed in wireshark, the connection from Coati to vim (connecting to 127.0.0.1:6666) failed. After executing :CoatiStartServer the :CoatiRefresh command works.

Improvements that would have saved time:

- A trouble-shooting section in the coati help for vim sayaing roughly "if :CoatiRefresh doesn't work, you forgot to start the server".
- Having CoatiRefresh display an error if the server isn't running yet (or starting it).
- Having Coati display an error if the connection to the editor fails.

Best regards
mpb

**Comment by st4ll1** [comment]
If the server is not running when executing :SourcetrailRefresh the plugin will try to start the server 
and display the you need to resend the command from Sourcetrail.
The plugin now displays an error if the connection fails.
