### ISSUE TITLE
Segfault on startup on Linux using vnc desktop.

### ISSUE THREAD

**Issue by TreyBoudreau** [CoatiSoftware/SourcetrailBugTracker#272]
Using a VNC desktop, Coati_0_10_0_Linux_64bit.tar.gz downloaded, extracted, and executed:
----------
trey@devel:~/Downloads/Coati$ ./Coati.sh 
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Segmentation fault

----------

**Comment by egraether** [comment]
@TreyBoudreau Thanks for reporting, we don't have an idea what's going on here yet.
Which Linux version are you using?

**Comment by TreyBoudreau** [comment]
trey@devel:dir$ uname -a
Linux devel 3.19.0-68-generic #76-Ubuntu SMP Fri Aug 12 08:48:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
trey@devel:dir$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by st4ll1** [comment]
@TreyBoudreau Which vnc server/client and version are you using?

**Comment by TreyBoudreau** [comment]
Server side: vnc4server  4.1.1+xorg4.3.0-37.3ubuntu2
Client side: VNC® Viewer 5.2.1 (r5668) x86 (Aug 18 2014 12:26:04) macOS

**Comment by st4ll1** [comment]
Ok i tested a VNC connection, i did not test it with the same client since i am on linux but i think thats not the problem. 
Looks like that a packages like **x11-xkb-utils** is missing on the server which is needed by Qt to run.

**Comment by TreyBoudreau** [comment]
I have the x11-xkb-utils installed, but the RANDR support looks like the root cause. I've tweaked my environment and use a different VNC server/X setup and it works for me now.

**Comment by egraether** [comment]
Looks like this got resolved, no more updates in 3 months. Closing.
