### ISSUE TITLE
Show Qt SIGNAL & SLOT calls

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#28]
Coati doesn't show a QT SLOT is calling a user provided function

**Comment by CocoaBeans** [comment]
+1

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Can be achieved by using [new Qt Signal Slot Syntax](https://wiki.qt.io/New_Signal_Slot_Syntax)
The old syntax can't be properly resolved at compile-time
