### ISSUE TITLE
How about fold code comment default in code window?

### ISSUE THREAD

**Issue by TonnyTao** [CoatiSoftware/SourcetrailBugTracker#304]
If comments been folded, It could help me focus on code.

**Comment by wrongway88** [comment]
Thanks for the suggestion. I will post as soon as we look into it.

**Comment by payload** [comment]
I just came into the situation, that I wanted to focus on code comments.
So I want to extend this feature request to something like the possibility of switching between focus on code, focus on comments.
Folding is one method to emphasize focus, but you already use it :)
I would suggest color fading, blending in and out.

I fall back to copy paste delete for now :)

**Comment by egraether** [comment]
@payload so you want a mode in which comments are emphasized instead of code? Like a different color scheme?

**Comment by payload** [comment]
@egraether yes.

**Comment by egraether** [comment]
Moving to #433
