### ISSUE TITLE
Need tidy in graphic, packages now are surround by class.

### ISSUE THREAD

**Issue by TonnyTao** [CoatiSoftware/SourcetrailBugTracker#307]
Mac
Coati 0.10.0

How about put package in first column ? 

![](https://i.imgsafe.org/d2fc215ba2.png)

**Comment by egraether** [comment]
@TonnyTao Is this issue still present in our latest build?

**Comment by egraether** [comment]
No clear feature/bug description, no updates in months. Closing.
