### ISSUE TITLE
On-Screen Help and Documentation

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/SourcetrailBugTracker#308]
There are too many "hidden" features in the UI (e.g. selecting text in code view or seperate graph zooming). At the very least there should be a toggle-able key-command list readily available.

**Comment by wrongway88** [comment]
Added a simple shortcut cheat sheet to the in-app help section.
It will be included in the next update.

Some more measures are still to come, but this at least provides a quickly accessible overview.

**Comment by egraether** [comment]
Added graph legend with 2018.2.122
Closing now and waiting for future requests on the matter
