### ISSUE TITLE
Call goes to undefined node instead of function node in C project

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#310]
In [neovim](https://github.com/neovim/neovim/):
`u_find_first_changed()` via the search doesn't show any functions calling it in the graph, but it's called in `readfile()`. In the graph view of `readfile()` we see a hashed out implicit `u_find_first_changed()` node. Similarly, `readfile()` is called in `open_buffer()` but only shown as a implicit function there.

**Comment by eau-u4f** [comment]
+1

**Comment by st4ll1** [comment]
I created a Coatiproject with the compilation database generated from CMake. Neovim setup: https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies. 
The mentioned calles are looking fine.
![readline](https://cloud.githubusercontent.com/assets/204582/22689319/ac6cfae0-ed30-11e6-8d79-96c456022fcc.png)
![u_find_first](https://cloud.githubusercontent.com/assets/204582/22689320/ac96e7a6-ed30-11e6-94d7-9f2016ea2138.png)



For further debugging we need a project setup that causes this failures.

**Comment by egraether** [comment]
Closing this issue due to no replies in 3 months, should be fixed.
