### ISSUE TITLE
Mouse warped when opening dialog windows (Refresh & others)

### ISSUE THREAD

**Issue by Krakonos** [CoatiSoftware/SourcetrailBugTracker#345]
Hi! I'm currently testing Coati and found an issue: the mouse is warped to my left monitor whenever a message dialog pops up (for example, the Refresh dialog).

I do have two monitor and i3 window manager, coati opened on my first main monitor (the right one). The window seems to briefly show up on the secondary monitor and is then moved over the coati window on my main monitor, however, the mouse stays there.

If I run coati on my secondary monitor (to the left), the mouse is not warped at all. 

This problem doesn't happy with other Qt applications (for example, Merkaartor) and is probably some artifact caused by the fancy custom dialogs without default decoration in Coati.

I'd really appreciate if this could be fixed.

Thanks!

**Comment by egraether** [comment]
Thanks for reporting. Which operating system do you use?

**Comment by Krakonos** [comment]
Linux (Arch), i3 window manager.

**Comment by st4ll1** [comment]
This behavior shoult be fix with the at Sourcetrail 0.13
