### ISSUE TITLE
Breaking Bug: No indexed files when creating project from compilation database

### ISSUE THREAD

**Issue by jpenalbae** [CoatiSoftware/SourcetrailBugTracker#366]
## Description

Sourcetrail is not able to create new projects using a compilation database, indexing 0 files.

It also happens when opening old projects, sourcetrail will try to re-index them, but 0 files will get indexed.

This is a breaking bug, as it renders sourcetrail unusable...

Also tried starting with a fresh installation by removing any previous config files from `~/.config/coati/` and `~/.config/sourcetrail/` without any luck.

## Environment

Sourcetrail: Sourcetrail_0_11_86_Linux_64bit
Distro: Debian unstable

## How to reproduce:

We can reproduce this by indexing the linux kernel

```
$ wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.10.10.tar.xz
$ tar Jxvf linux-4.10.10.tar.xz
$ cd linux-4.10.10/
$ make defconfig
$ bear make -j12 bzImage
```

This will generate a compile_commands.json file, which we will load into sourcetrail. The generated compilation database is attached: [compile_commands.json.zip](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/921724/compile_commands.json.zip)

* Create a new project
* C -> C/C++ from Compilation Database
* Select the generated compile_commands.json as compilation database
    * Sourcetrail will display message: 2215 source files were found in the compilation database
* Do not add any indexed header paths or add some, it doesn't really make any difference.
* Finish project creation
    * Sourcetrail will display "Start indexing" "Index: 0 Files"
* Press start button to start indexing.
* Nothing gets indexed....

This used to work perfectly, but it does not work any more, rendering sourcetrail totally useless to me....

![project](https://cloud.githubusercontent.com/assets/8380459/25037988/797d79d4-20fc-11e7-8559-20d4cf5c6c07.png)

![start-indexing](https://cloud.githubusercontent.com/assets/8380459/25037705/ed046dd8-20fa-11e7-8b75-01edc94e50ba.png)

![start-indexing2](https://cloud.githubusercontent.com/assets/8380459/25037709/f20f67ec-20fa-11e7-9c88-2a68bb81f68c.png)

**Comment by egraether** [comment]
@jpenalbae Thank you for reporting and providing all this information! We think we could figure out the origin of the problem.

Our current release accidentally saves C++ specific source extensions and standard information to the project file for all created compilation database projects. To fix this please open the `.srctrlprj` file in a text editor and remove these tags:

```
...
            <source_extensions>
                <source_extension>.cpp</source_extension>
                <source_extension>.cxx</source_extension>
                <source_extension>.cc</source_extension>
            </source_extensions>
            <standard>c++1z</standard>
...
```
Then the project should work as it used to and index all files from the compilation database. Can you please try this and let us know if it works?

**Comment by jpenalbae** [comment]
Replacing `source_extensions` with the following seems start the indexing process:

```
            <source_extensions>>
                <source_extension>.c</source_extension>
            </source_extensions>
```

Anyway, I'm getting thousands of errors per file while indexing, so I guess I should stick to an older version for now....

**Comment by egraether** [comment]
@jpenalbae Did you try removing the whole `source_extensions` tag and the `standard` tag?

**Comment by jpenalbae** [comment]
Unknown types mostly iirc....

Just removing the hole `<source_extensions>` block does not index anything. Yes I also did remove the `standard` tag, and tried using `c` and `gnu99` for it.

Anyway, do not worry about it, I just rolled back to `0.11.15`. Having to edit the project file by hand and reloading it, is not an option for me. I will try again on the next version once this gets fixed.

**Comment by egraether** [comment]
Fixed saving of C++ specific source extensions and standard information for new Compilation Database projects with 0.11.89

I have no idea yet why this issue would cause any new errors.

**Comment by jpenalbae** [comment]
New errors might be my fault while editing the project file, dunno... I will check it once 0.11.89 is released.

Btw, thanks for the quick fix 👍

**Comment by jpenalbae** [comment]
Seems to be working fine again under 0.12 (beta)

Thanks!!!
