### ISSUE TITLE
Cross compile handling

### ISSUE THREAD

**Issue by fedegiova** [CoatiSoftware/SourcetrailBugTracker#370]
Hi, actually coati seems to use the x86 version of clang for indexing, this means that it's not able to index correctly arm code, for example indexing the linux kernel using a compilation database produces thousands of "unknown register name rx in asm" errors. 

Any ideas on how to fix this? At least for arm since it's a widely used platform.

**Comment by mlangkabel** [comment]
Hi @fedegiova, this is a good question. We haven't thoroughly tested cross compilation yet, but it seems like clang offers an option for that. You can set the option in your project settings by adding a line to the "Compiler Flags" listbox. 

The option is called --target and you can find more information on how to configure it [here](https://clang.llvm.org/docs/CrossCompilation.html).

As an example I'd set the following option for a project that should be build on a windows pc:
`--target=x86_64-pc-win32-unknown`

**Comment by fedegiova** [comment]
Thank you for the suggestion, I've updated the compilation database replacing the -march switch
with --target=arm-linux-gnueabi and now it's working much better!

**Comment by egraether** [comment]
Added a UI component for defining the cross-compilation triple with v2017.2.69 to make this easier in the future.
