### ISSUE TITLE
VS Plugin fails + manual setup causes crash on indexing

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/SourcetrailBugTracker#371]
VS plugin (latest release) fails to generate cdb, results in empty .json file
see log file

[Log_SourcetrailPlugin_2017-4-26_14-38-7.txt](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/958419/Log_SourcetrailPlugin_2017-4-26_14-38-7.txt)

Tried manual setup, causes indexing crash after 5 or 6 indexed files.
Can neither provide project nor log file, since it contains project- and file names + structure

**Comment by mlangkabel** [comment]
Plugin issue has probably been fixed with Sourcetrail 0.12.64. We are planning on releasing that version next week.

**Comment by mlangkabel** [comment]
Version 1.0 of the Visual Studio extension is now available in the VS gallery. To update just click `Tools` -> `Extensions and Updates...`. Under the `Updates` section choose to update the `Sourcetrail Extension` entry.

Please check if the issue still exists.

**Comment by mlangkabel** [comment]
Closing this issue now because it's probably already resolved and we haven't received any further feedback. Please post new issues regarding the Visual Studio extension to the [Sourcetrail Extension issue tracker](https://github.com/CoatiSoftware/vs-sourcetrail/issues).
