### ISSUE TITLE
Java: import gradle projects

### ISSUE THREAD

**Issue by mkurdej** [CoatiSoftware/SourcetrailBugTracker#379]
It would be nice to have a possibility to import projects using gradle, not only maven.

**Comment by egraether** [comment]
+1 via [tweet](https://twitter.com/xgouchet/status/878177502375534593)

**Comment by shoito** [comment]
+1

**Comment by egraether** [comment]
+1 via mail

**Comment by egraether** [comment]
+1 via mail

**Comment by egraether** [comment]
+1 via mail

**Comment by steelejoe** [comment]
+1

**Comment by mlangkabel** [comment]
Status update: We just started working on this. So this may be part of the next release!

**Comment by mlangkabel** [comment]
Implemented with Sourcetrail version 2017.3.68
