### ISSUE TITLE
No indexed files when creating project from compilation database

### ISSUE THREAD

**Issue by fedegiova** [CoatiSoftware/SourcetrailBugTracker#391]
## Description

I've created a c++ project with a compilation database but no files get indexed, I've encountered this bug before but I was able to get by deleting the "source extensions" tag as in: [https://github.com/CoatiSoftware/SourcetrailBugTracker/issues/366](url) 

## Environment
Sourcetrail: Sourcetrail_0_12_25_Linux_64bit
Distro: Debian unstable

## How to reproduce

cd Project
bear make all

this will generate the compilation database file, then I'll create a C++ project with it, configure everything, the indexer start but no file get actually indexed. Moreover the project files get listed correctly in the show-source-files window.

![image](https://cloud.githubusercontent.com/assets/15714045/26451203/4e933b1c-415b-11e7-81ca-b3b2d9a45e6f.png)

this is the project file: 
[Project.srctrlprj.txt](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/1029024/Project.srctrlprj.txt)

this is an extract of the logs from sourcetrail:
`
14:57:36 | INFO: send MessageStatus Preparing Project: Processing Files - loading
14:57:36 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Preparing Project: Processing Files
14:57:36 | INFO: send MessageStatus 
14:57:36 | INFO: send MessageWindowFocus 
14:57:39 | INFO: send MessageWindowFocus 
14:57:39 | INFO: send MessageStatus Reindexing Project - loading
14:57:39 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Reindexing Project
14:57:39 | INFO: send MessageClearErrorCount 
14:57:43 | INFO: send MessageStatus 
14:57:43 | INFO: send MessagePingReceived 
14:57:43 | INFO: send MessagePingReceived 
14:57:43 | INFO: send MessagePingReceived 
14:57:43 | INFO: send MessagePingReceived 
14:57:43 | INFO: send MessageStatus Finish Indexing: Optimizing database - loading
14:57:43 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finish Indexing: Optimizing database
14:57:44 | Blackboard.h:91 get() | WARNING: Entry for "indexed_source_file_count" not found on blackboard.
14:57:44 | Blackboard.h:91 get() | WARNING: Entry for "source_file_count" not found on blackboard.
14:57:44 | Blackboard.h:91 get() | WARNING: Entry for "interrupted_indexing" not found on blackboard.
14:57:44 | INFO: send MessageStatus Finish Indexing: Building caches - loading
14:57:44 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finish Indexing: Building caches
14:57:44 | INFO: send MessageStatus 
14:57:44 | INFO: send MessageFinishedParsing 
14:57:44 | INFO: send MessageStatus Finished indexing: 0/0 source files indexed; 00:00:00:919; 0 errors
14:57:44 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finished indexing: 0/0 source files indexed; 00:00:00:919; 0 errors
14:57:44 | Application.cpp:369 logStorageStats() | INFO: 
Graph:
        0 Nodes
        0 Edges

Code:
        0 Files
        0 Lines of Code

Errors:
        0 Errors
        0 Fatal Errors

14:57:44 | INFO: send MessageWindowFocus 
14:57:44 | INFO: send MessageRefresh ui 
14:57:44 | INFO: send MessagePingReceived 
`
this is the compilation database: 
[compile_commands.json.zip](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/1029031/compile_commands.json.zip)

**Comment by egraether** [comment]
Thank you for reporting. This was actually already reported with #388.
There is a bug in our current release that wrongly handles relative file paths within the `compile_commands.json` file. It will be fixed in the new release.

As a workaround you can either turn your relative paths to absolute ones:
Replace `"file": "../..` with `"file": "/home/fede/workspace/Project/`
Replace `"file": "src` with `"file": "/home/fede/workspace/Project/src`

Or you can use an older version of Bear (2.2.1) that still uses absolute paths as suggested here: rizsotto/Bear#159

**Comment by fedegiova** [comment]
Sorry, I've done the rename and also tried to recreate the database with bear 2.2.1. Now it finds the files but instead of indexing them is only running through the list very fast. Its taking 8 seconds for 1200 files and I'm not running a supercomputer. I've added some excerpts from the console logs.

Please note that the same pbd gets indexed correctly by Coati 0.11

`
8:40:23 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Indexing files: [2/1220] /home/fede/workspace/Project/src/gtk/src/agents/BuzzerManagerProxy.cpp
08:40:23 | INFO: send MessageStatus Indexing files: [2/1220] /home/fede/workspace/Project/build/Delta80_imx6_release.assert/src/ValvesBravo400SLTSprayer/ValvesBravo400SLTSprayerSettings.settings.cpp - loading
08:40:23 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Indexing files: [2/1220] /home/fede/workspace/Project/build/Delta80_imx6_release.assert/src/ValvesBravo400SLTSprayer/ValvesBravo400SLTSprayerSettings.settings.cpp
08:40:23 | INFO: send MessageStatus Indexing files: [2/1220] /home/fede/workspace/Project/src/DomainModel/src/ModelParts/MassExport/MassExporter.cpp - loading
08:40:23 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Indexing files: [2/1220] /home/fede/workspace/Project/src/DomainModel/src/ModelParts/MassExport/MassExporter.cpp
08:40:23 | INFO: send MessageStatus Indexing files: [2/1220] /home/fede/workspace/Project/src/GtkServer/src/elements/IndexBuffer.cpp - loading
08:40:23 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Indexing files: [2/1220] /home/fede/workspace/Project/src/GtkServer/src/elements/IndexBuffer.cpp
08:40:23 | INFO: send MessageStatus Indexing files: [2/1220] /home/fede/workspace/Project/src/Collaudo/CollaudoDelta/src/tests/AudioTest.cpp - loading
08:40:23 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Indexing files: [2/1220] /home/fede/workspace/Project/src/Collaudo/CollaudoDelta/src/tests/AudioTest.cpp
08:40:23 | INFO: send MessageStatus Indexing files: [2/1220] /home/fede/workspace/Project/src/Installer/NovatelUpdater/NUSmartAg/src/main.cpp - loading
0
`
`
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 2 - storage count: 5
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 3 - storage count: 5
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 1 - storage count: 4
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 4 - storage count: 5
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 2 - storage count: 4
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 3 - storage count: 4
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 1 - storage count: 3
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 4 - storage count: 4
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 3 - storage count: 3
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 2 - storage count: 3
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 4 - storage count: 3
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 3 - storage count: 2
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 1 - storage count: 2
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 2 - storage count: 2
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 4 - storage count: 2
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 3 - storage count: 1
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 2 - storage count: 1
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 4 - storage count: 1
08:40:25 | TaskBuildIndex.cpp:248 fetchIntermediateStorages() | INFO: 1 - storage count: 1
08:40:25 | INFO: send MessageStatus Finish Indexing: Saving Remaining Data - loading
08:40:25 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finish Indexing: Saving Remaining Data
08:40:25 | INFO: send MessageWindowFocus 
08:40:26 | INFO: send MessageStatus Finish Indexing: Optimizing database - loading
08:40:26 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finish Indexing: Optimizing database
08:40:27 | Blackboard.h:91 get() | WARNING: Entry for "interrupted_indexing" not found on blackboard.
08:40:27 | INFO: send MessageStatus Finish Indexing: Building caches - loading
08:40:27 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finish Indexing: Building caches
08:40:27 | INFO: send MessageStatus 
08:40:27 | INFO: send MessageFinishedParsing 
08:40:27 | INFO: send MessageStatus Finished indexing: 1220/1220 source files indexed; 00:00:08:564; 0 errors
08:40:27 | StatusBarController.cpp:75 setStatus() | INFO: STATUS Finished indexing: 1220/1220 source files indexed; 00:00:08:564; 0 errors
08:40:27 | INFO: send MessageWindowFocus 
08:40:27 | Application.cpp:369 logStorageStats() | INFO: 
Graph:
        0 Nodes
        0 Edges

Code:
        0 Files
        0 Lines of Code

Errors:
        0 Errors
        0 Fatal Errors

08:40:27 | INFO: send MessagePingReceived 
08:40:27 | INFO: send MessageRefresh ui 
08:40:27 | INFO: send MessagePingReceived 
08:40:27 | INFO: send MessageActivateAll 

`

**Comment by egraether** [comment]
Can you please send us your project file, your updated compilation database and the full log file to mail@sourcetrail.com?

**Comment by egraether** [comment]
It seems that the issue is caused by the `-march=armv7-a` flag in your compile commands. For some reason clang can't cope with this architecture and just silently fails without any information in the console output.

I couldn't find any arm architecture replacement flag that works either.

Please replace all occurrences of `"-march=armv7-a"` with `""` in your `compile_commands.json`, try again and let me know what happens.

**Comment by fedegiova** [comment]
Now it's working fine, thanks
