### ISSUE TITLE
[OSX] Compile_commands.json blank source files

### ISSUE THREAD

**Issue by mtowalski** [CoatiSoftware/SourcetrailBugTracker#395]
OS: Mac OSX Sierra 10.12.5

I am trying to create project from compile_commands.json.
When parsing is done all I can see is the graph no source code.
I can lookup names etc. but references will now show up.

Screenshot of the problem:
[http://i.imgur.com/tpCEBm3.png](http://i.imgur.com/tpCEBm3.png)

**Comment by egraether** [comment]
How did you create the compile_commands.json?
I think this is already resolved. We will release a new beta build tomorrow, I will let you know when it's ready.

**Comment by egraether** [comment]
New beta build is now available: https://www.sourcetrail.com/downloads#beta
Please check if your problem still persists with the new build.

**Comment by mtowalski** [comment]
Hi, yep with beta works perfect. 👍
