### ISSUE TITLE
VScode plugin

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#397]
via HN: https://news.ycombinator.com/item?id=14612440#14613360

**Comment by AngelEzquerra** [comment]
I just discovered SourceTrail. I plan to start a trial to evaluate if would be useful for my team. We use Eclipse, Visual Studio and Visual Studio Code so it would be great if SourceTrail supported VS Code as well.

**Comment by egraether** [comment]
+1 by mail

**Comment by st4ll1** [comment]
VS Code extension is now available in the marketplace, just search for sourcetrail.

soucecode at: https://github.com/CoatiSoftware/vsce-sourcetrail
