### ISSUE TITLE
Crash when clicking on a non indexed class (with QtCreatorPlugin)

### ISSUE THREAD

**Issue by snsmac** [CoatiSoftware/SourcetrailBugTracker#400]
OS:Ubuntu 17.04
Kernel: 4.10.0-22-generic
Stacktrace:

> Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
*** Error in `/home/xxx/Downloads/Sourcetrail/Sourcetrail': double free or corruption (out): 0x0000000003523800 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7fb153aef08b]
/lib/x86_64-linux-gnu/libc.so.6(+0x82c3a)[0x7fb153af8c3a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fb153afcd2c]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Widgets.so.5(_ZN13QGraphicsItemD1Ev+0x256)[0x7fb15658c606]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZN11QtGraphNodeD1Ev+0x2b6)[0x82ce96]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZN11QtGraphNodeD1Ev+0x135)[0x82cd15]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZNSt4listISt10shared_ptrI11QtGraphNodeESaIS2_EEaSERKS4_+0x175)[0x77cee5]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZN11QtGraphView20switchToNewGraphDataEv+0x14e)[0x77bd6e]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZN11QtGraphView14doRebuildGraphESt10shared_ptrI5GraphERKSt6vectorIS0_I9DummyNodeESaIS5_EERKS3_IS0_I9DummyEdgeESaISB_EEN9GraphView11GraphParamsE+0x70)[0x776480]
/home/xxx/Downloads/Sourcetrail/Sourcetrail[0x782c65]
/home/xxx/Downloads/Sourcetrail/Sourcetrail[0x783467]
/home/xxx/Downloads/Sourcetrail/Sourcetrail[0x7832dd]
/home/xxx/Downloads/Sourcetrail/Sourcetrail[0x7c33b5]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xc1)[0x7fb1551c7141]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fb1562c243c]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x227)[0x7fb1562c9867]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x108)[0x7fb15519c118]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x2db)[0x7fb15519e4fb]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x34)[0x7fb1551ea514]
/home/xxx/Downloads/Sourcetrail/lib/libQt5XcbQpa.so.5(+0xadd0d)[0x7fb14f66dd0d]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xea)[0x7fb15519a8ca]
/home/xxx/Downloads/Sourcetrail/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x84)[0x7fb1551a2ca4]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(_ZN13QtApplication4execEv+0xf2)[0x75b902]
/home/xxx/Downloads/Sourcetrail/Sourcetrail(main+0x1f7a)[0x751a1a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fb153a963f1]
/home/xxx/Downloads/Sourcetrail/Sourcetrail[0x74c765]
======= Memory map: ========
00400000-01d34000 r-xp 00000000 08:13 8126583                            /home/xxx/Downloads/Sourcetrail/Sourcetrail
01f33000-02026000 rw-p 01933000 08:13 8126583                            /home/xxx/Downloads/Sourcetrail/Sourcetrail
02026000-0202d000 rw-p 00000000 00:00 0 
02d63000-04805000 rw-p 00000000 00:00 0                                  [heap]
7fb110000000-7fb110021000 rw-p 00000000 00:00 0 
7fb110021000-7fb114000000 ---p 00000000 00:00 0 
7fb118000000-7fb1195f9000 rw-p 00000000 00:00 0 
7fb1195f9000-7fb11c000000 ---p 00000000 00:00 0 
7fb120000000-7fb120021000 rw-p 00000000 00:00 0 
7fb120021000-7fb124000000 ---p 00000000 00:00 0 
7fb124000000-7fb124021000 rw-p 00000000 00:00 0 
7fb124021000-7fb128000000 ---p 00000000 00:00 0 
7fb128000000-7fb128021000 rw-p 00000000 00:00 0 
7fb128021000-7fb12c000000 ---p 00000000 00:00 0 
7fb12c000000-7fb12c2be000 rw-p 00000000 00:00 0 
7fb12c2be000-7fb130000000 ---p 00000000 00:00 0 
7fb1337ff000-7fb133800000 ---p 00000000 00:00 0 
7fb133800000-7fb134000000 rw-p 00000000 00:00 0 
7fb134000000-7fb134021000 rw-p 00000000 00:00 0 
7fb134021000-7fb138000000 ---p 00000000 00:00 0 
7fb138000000-7fb13c000000 rw-p 00000000 00:00 0 
7fb13c000000-7fb13c026000 rw-p 00000000 00:00 0 
7fb13c026000-7fb140000000 ---p 00000000 00:00 0 
7fb140000000-7fb140021000 rw-p 00000000 00:00 0 
7fb140021000-7fb144000000 ---p 00000000 00:00 0 
7fb14466d000-7fb14466e000 ---p 00000000 00:00 0 
7fb14466e000-7fb144e6e000 rw-p 00000000 00:00 0 
7fb144e6e000-7fb144e6f000 ---p 00000000 00:00 0 
7fb144e6f000-7fb14566f000 rw-p 00000000 00:00 0 
7fb14566f000-7fb145670000 ---p 00000000 00:00 0 
7fb145670000-7fb145e70000 rw-p 00000000 00:00 0 
7fb145e70000-7fb145e71000 ---p 00000000 00:00 0 
7fb145e71000-7fb146671000 rw-p 00000000 00:00 0 
7fb146671000-7fb146dea000 rw-s 00000000 00:05 19300364                   /SYSV00000000 (deleted)
7fb146dea000-7fb146deb000 ---p 00000000 00:00 0 
7fb146deb000-7fb1475eb000 rw-p 00000000 00:00 0 
7fb1475eb000-7fb1475ec000 ---p 00000000 00:00 0 
7fb1475ec000-7fb147dec000 rw-p 00000000 00:00 0 
7fb147dec000-7fb147dff000 r-xp 00000000 08:13 5767448                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7fb147dff000-7fb147ffe000 ---p 00013000 08:13 5767448                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7fb147ffe000-7fb147fff000 r--p 00012000 08:13 5767448                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7fb147fff000-7fb148000000 rw-p 00013000 08:13 5767448                    /lib/x86_64-linux-gnu/libgpg-error.so.0.21.0
7fb148000000-7fb148021000 rw-p 00000000 00:00 0 
7fb148021000-7fb14c000000 ---p 00000000 00:00 0 
7fb14c0ef000-7fb14c1f6000 r-xp 00000000 08:13 5767450                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7fb14c1f6000-7fb14c3f5000 ---p 00107000 08:13 5767450                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7fb14c3f5000-7fb14c3f7000 r--p 00106000 08:13 5767450                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7fb14c3f7000-7fb14c3fe000 rw-p 00108000 08:13 5767450                    /lib/x86_64-linux-gnu/libgcrypt.so.20.1.6
7fb14c3fe000-7fb14c415000 r-xp 00000000 08:13 140148                     /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
7fb14c415000-7fb14c614000 ---p 00017000 08:13 140148                     /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
7fb14c614000-7fb14c615000 r--p 00016000 08:13 140148                     /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
7fb14c615000-7fb14c616000 rw-p 00017000 08:13 140148                     /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
7fb14c616000-7fb14c63a000 r-xp 00000000 08:13 5767354                    /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7fb14c63a000-7fb14c83a000 ---p 00024000 08:13 5767354                    /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7fb14c83a000-7fb14c83b000 r--p 00024000 08:13 5767354                    /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7fb14c83b000-7fb14c83c000 rw-p 00025000 08:13 5767354                    /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7fb14c83c000-7fb14c83d000 ---p 00000000 00:00 0 
7fb14c83d000-7fb14d43e000 rw-p 00000000 00:00 0 
7fb14d48d000-7fb14d53a000 r--p 00000000 08:13 1313094                    /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
7fb14d53a000-7fb14d5f3000 r--p 00000000 08:13 1313095                    /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
7fb14d5f3000-7fb14d63d000 r-xp 00000000 08:13 5767425                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.7
7fb14d63d000-7fb14d83d000 ---p 0004a000 08:13 5767425                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.7
7fb14d83d000-7fb14d83e000 r--p 0004a000 08:13 5767425                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.7
7fb14d83e000-7fb14d83f000 rw-p 0004b000 08:13 5767425                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.7
7fb14d83f000-7fb14d840000 ---p 00000000 00:00 0 
7fb14d840000-7fb14e040000 rw-p 00000000 00:00 0 
7fb14e040000-7fb14e049000 r-xp 00000000 08:13 8913271                    /home/xxx/Downloads/Sourcetrail/lib/libXrender.so.1
7fb14e049000-7fb14e248000 ---p 00009000 08:13 8913271                    /home/xxx/Downloads/Sourcetrail/lib/libXrender.so.1
7fb14e248000-7fb14e249000 rw-p 00008000 08:13 8913271                    /home/xxx/Downloads/Sourcetrail/lib/libXrender.so.1
7fb14e249000-7fb14e252000 r-xp 00000000 08:13 139309                     /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fb14e252000-7fb14e451000 ---p 00009000 08:13 139309                     /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fb14e451000-7fb14e452000 r--p 00008000 08:13 139309                     /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fb14e452000-7fb14e453000 rw-p 00009000 08:13 139309                     /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fb14e453000-7fb14e454000 ---p 00000000 00:00 0 
7fb14e454000-7fb14ec54000 rw-p 00000000 00:00 0 
7fb14ec54000-7fb14ec63000 r-xp 00000000 08:13 8913282                    /home/xxx/Downloads/Sourcetrail/lib/libXi.so.6
7fb14ec63000-7fb14ee62000 ---p 0000f000 08:13 8913282                    /home/xxx/Downloads/Sourcetrail/lib/libXi.so.6
7fb14ee62000-7fb14ee63000 rw-p 0000e000 08:13 8913282                    /home/xxx/Downloads/Sourcetrail/lib/libXi.so.6
7fb14ee63000-7fb14eeeb000 r-xp 00000000 08:13 8913281                    /home/xxx/Downloads/Sourcetrail/lib/libQt5DBus.so.5
7fb14eeeb000-7fb14f0ea000 ---p 00088000 08:13 8913281                    /home/xxx/Downloads/Sourcetrail/lib/libQt5DBus.so.5
7fb14f0ea000-7fb14f0ec000 rw-p 00087000 08:13 8913281                    /home/xxx/Downloads/Sourcetrail/lib/libQt5DBus.so.5
7fb14f0ec000-7fb14f0ed000 rw-p 00000000 00:00 0 
7fb14f0ed000-7fb14f185000 r-xp 00000000 08:13 8913284                    /home/xxx/Downloads/Sourcetrail/lib/libfreetype.so.6
7fb14f185000-7fb14f384000 ---p 00098000 08:13 8913284                    /home/xxx/Downloads/Sourcetrail/lib/libfreetype.so.6
7fb14f384000-7fb14f38a000 rw-p 00097000 08:13 8913284                    /home/xxx/Downloads/Sourcetrail/lib/libfreetype.so.6
7fb14f38a000-7fb14f3be000 r-xp 00000000 08:13 8913290                    /home/xxx/Downloads/Sourcetrail/lib/libfontconfig.so.1
7fb14f3be000-7fb14f5be000 ---p 00034000 08:13 8913290                    /home/xxx/Downloads/Sourcetrail/lib/libfontconfig.so.1
7fb14f5be000-7fb14f5c0000 rw-p 00034000 08:13 8913290                    /home/xxx/Downloads/Sourcetrail/lib/libfontconfig.so.1
7fb14f5c0000-7fb14f708000 r-xp 00000000 08:13 8913292                    /home/xxx/Downloads/Sourcetrail/lib/libQt5XcbQpa.so.5
7fb14f708000-7fb14f907000 ---p 00148000 08:13 8913292                    /home/xxx/Downloads/Sourcetrail/lib/libQt5XcbQpa.so.5
7fb14f907000-7fb14f912000 rw-p 00147000 08:13 8913292                    /home/xxx/Downloads/Sourcetrail/lib/libQt5XcbQpa.so.5
7fb14f912000-7fb14f914000 r-xp 00000000 08:13 8913279                    /home/xxx/Downloads/Sourcetrail/lib/platforms/libqxcb.so
7fb14f914000-7fb14fb13000 ---p 00002000 08:13 8913279                    /home/xxx/Downloads/Sourcetrail/lib/platforms/libqxcb.so
7fb14fb13000-7fb14fb14000 rw-p 00001000 08:13 8913279                    /home/xxx/Downloads/Sourcetrail/lib/platforms/libqxcb.so
7fb14fb14000-7fb14ff70000 r--p 00000000 08:13 135010                     /usr/lib/locale/locale-archive
7fb14ff70000-7fb14ff72000 r-xp 00000000 08:13 8913257                    /home/xxx/Downloads/Sourcetrail/lib/libXau.so.6
7fb14ff72000-7fb150172000 ---p 00002000 08:13 8913257                    /home/xxx/Downloads/Sourcetrail/lib/libXau.so.6
7fb150172000-7fb150173000 rw-p 00002000 08:13 8913257                    /home/xxx/Downloads/Sourcetrail/lib/libXau.so.6
7fb150173000-7fb15019a000 r-xp 00000000 08:13 5767429                    /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7fb15019a000-7fb15039a000 ---p 00027000 08:13 5767429                    /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7fb15039a000-7fb15039c000 r--p 00027000 08:13 5767429                    /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7fb15039c000-7fb15039d000 rw-p 00029000 08:13 5767429                    /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7fb15039d000-7fb1503aa000 r-xp 00000000 08:13 8913258                    /home/xxx/Downloads/Sourcetrail/lib/libdrm.so.2
7fb1503aa000-7fb1505a9000 ---p 0000d000 08:13 8913258                    /home/xxx/Downloads/Sourcetrail/lib/libdrm.so.2
7fb1505a9000-7fb1505aa000 rw-p 0000c000 08:13 8913258                    /home/xxx/Downloads/Sourcetrail/lib/libdrm.so.2
7fb1505aa000-7fb1505ae000 r-xp 00000000 08:13 8913291                    /home/xxx/Downloads/Sourcetrail/lib/libXxf86vm.so.1
7fb1505ae000-7fb1507ae000 ---p 00004000 08:13 8913291                    /home/xxx/Downloads/Sourcetrail/lib/libXxf86vm.so.1
7fb1507ae000-7fb1507af000 rw-p 00004000 08:13 8913291                    /home/xxx/Downloads/Sourcetrail/lib/libXxf86vm.so.1
7fb1507af000-7fb1507d3000 r-xp 00000000 08:13 8913263                    /home/xxx/Downloads/Sourcetrail/lib/libxcb.so.1
7fb1507d3000-7fb1509d3000 ---p 00024000 08:13 8913263                    /home/xxx/Downloads/Sourcetrail/lib/libxcb.so.1
7fb1509d3000-7fb1509d4000 rw-p 00024000 08:13 8913263                    /home/xxx/Downloads/Sourcetrail/lib/libxcb.so.1
7fb1509d4000-7fb1509d7000 r-xp 00000000 08:13 8913293                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-dri2.so.0
7fb1509d7000-7fb150bd7000 ---p 00003000 08:13 8913293                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-dri2.so.0
7fb150bd7000-7fb150bd8000 rw-p 00003000 08:13 8913293                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-dri2.so.0
7fb150bd8000-7fb150bef000 r-xp 00000000 08:13 8913255                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-glx.so.0
7fb150bef000-7fb150dee000 ---p 00017000 08:13 8913255                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-glx.so.0
7fb150dee000-7fb150df0000 rw-p 00016000 08:13 8913255                    /home/xxx/Downloads/Sourcetrail/lib/libxcb-glx.so.0
7fb150df0000-7fb150f27000 r-xp 00000000 08:13 8913283                    /home/xxx/Downloads/Sourcetrail/lib/libX11.so.6
7fb150f27000-7fb151127000 ---p 00137000 08:13 8913283                    /home/xxx/Downloads/Sourcetrail/lib/libX11.so.6
7fb151127000-7fb15112d000 rw-p 00137000 08:13 8913283                    /home/xxx/Downloads/Sourcetrail/lib/libX11.so.6
7fb15112d000-7fb15112e000 r-xp 00000000 08:13 8913286                    /home/xxx/Downloads/Sourcetrail/lib/libX11-xcb.so.1
7fb15112e000-7fb15132d000 ---p 00001000 08:13 8913286                    /home/xxx/Downloads/Sourcetrail/lib/libX11-xcb.so.1
7fb15132d000-7fb15132e000 rw-p 00000000 08:13 8913286                    /home/xxx/Downloads/Sourcetrail/lib/libX11-xcb.so.1
7fb15132e000-7fb151333000 r-xp 00000000 08:13 8913288                    /home/xxx/Downloads/Sourcetrail/lib/libXfixes.so.3
7fb151333000-7fb151532000 ---p 00005000 08:13 8913288                    /home/xxx/Downloads/Sourcetrail/lib/libXfixes.so.3
7fb151532000-7fb151533000 rw-p 00004000 08:13 8913288                    /home/xxx/Downloads/Sourcetrail/lib/libXfixes.so.3Aborted (core dumped)

**Comment by st4ll1** [comment]
@snsmac could provide more information about the crash. 
For example the steps to reproduce the crash.
If you have a open source project example or a project you can share 
where the crash happens would help us.

**Comment by snsmac** [comment]
@st4ll1 I am not sure what I changed in my setup, but im not able to reproduce the crash anymore
