### ISSUE TITLE
Maven imports not working as expected

### ISSUE THREAD

**Issue by sriprasanna** [CoatiSoftware/SourcetrailBugTracker#403]
Importing a new Maven project indexes files as expected but spews errors such as `Import not found: javax.persistence.Entity`, `Import not found: org.springframework.web.bind.annotation.RequestBody` etc

**Comment by mlangkabel** [comment]
Hi @sriprasanna, thanks for reporting this issue! My first guess is that the Maven integration somehow misses the jars that define those imported symbols. Can you please check if the folder `<sourcetrail_project_path>/sourcetrail_dependencies/<project_name>/maven/` contains these jar files? The jar for `javax.persistence.Entity` is probably called `persistence-api-1.0.2.jar`.

**Comment by mattconzen** [comment]
I have a similar issue. I tried creating a project using this source as an example/test run: 
https://github.com/eliast/dropwizard-guice-example

...but I get import not found for `com.codahale.metrics.annotation.Timed`
<img width="967" alt="image" src="https://user-images.githubusercontent.com/15315946/27489060-c9c4a014-57fe-11e7-9b9f-69b60ba39282.png">

This should be a part of the Dropwizard Metrics package, which is in my `/sourcetrail_dependencies/<project>/maven` directory.

```
~/SourceTrail/sourcetrail_dependencies/Test_Project/maven » ls | grep dropwizard-metrics                                                                                           
dropwizard-metrics-0.8.4.jar
metrics-annotation-3.1.1.jar
metrics-core-3.1.1.jar
metrics-healthchecks-3.1.1.jar
metrics-jersey2-3.1.1.jar
metrics-jetty9-3.1.1.jar
metrics-json-3.1.1.jar
metrics-jvm-3.1.1.jar
metrics-logback-3.1.1.jar
metrics-servlets-3.1.1.jar
```

**Comment by mlangkabel** [comment]
@mattconzen thanks for providing that example! I had to edit the pom a little bit (because you are using the snapshot version of `dropwizard-guice`) and now I can reproduce the error.

**Comment by mlangkabel** [comment]
When using `jar tf` to peek inside the `dropwizard-metrics` jar (I use version 7.0 because 8.4 doesn't seem to be available) I get the following output:
```
META-INF/
META-INF/MANIFEST.MF
io/
io/dropwizard/
io/dropwizard/metrics/
META-INF/services/
io/dropwizard/metrics/BaseFormattedReporterFactory.class
io/dropwizard/metrics/BaseReporterFactory$1.class
io/dropwizard/metrics/BaseReporterFactory.class
io/dropwizard/metrics/ConsoleReporterFactory$ConsoleStream.class
io/dropwizard/metrics/ConsoleReporterFactory.class
io/dropwizard/metrics/CsvReporterFactory.class
io/dropwizard/metrics/MetricsFactory.class
io/dropwizard/metrics/ReporterFactory.class
io/dropwizard/metrics/ScheduledReporterManager.class
io/dropwizard/metrics/Slf4jReporterFactory.class
META-INF/services/io.dropwizard.jackson.Discoverable
META-INF/services/io.dropwizard.metrics.ReporterFactory
META-INF/maven/
META-INF/maven/io.dropwizard/
META-INF/maven/io.dropwizard/dropwizard-metrics/
META-INF/maven/io.dropwizard/dropwizard-metrics/pom.xml
META-INF/maven/io.dropwizard/dropwizard-metrics/pom.properties
```

`com.codahale.metrics.annotation.Timed` doesn't seem to be in there.

**Comment by godeater** [comment]
I've got a similar issue with the jar files from Vertx.

For example, I've got multiple reports of "Import not found: io.vertx.core.Vertx".

All of the jars are in the <sourcetrail_project_path>/sourcetrail_dependencies/<project_name>/maven/ folder, and if I expand the jars, I can see the classes which SourceTrail is claiming are missing, and in the specific example above, I see 

io/vertx/core/Vertx.class

in the output of jar tf on the jar files in the sourcetrail_dependencies dir.

**Comment by mlangkabel** [comment]
@godeater: I just tried to reproduce the issue you are describing but I manually created the project by choosing the "Empty Java Source Group". In that case Sourcetrail successfully resolved an import for `io.vertx.core.Vertx`.

Could you please try the same and let me know if that gives a better result? Just create a new project, choose the "Empty Java Source Group" add you source directory to the "Indexed Paths" and drag&drop all the .jar files from your <sourcetrail_project_path>/sourcetrail_dependencies/<project_name>/maven/ folder into the "Class Path".

**Comment by godeater** [comment]
Yes, that worked better for some reason - I'm still left with one import not found message - but all the Vertx errors have disappeared.

**Comment by mlangkabel** [comment]
Please have a look at issue #418. Maybe that helps :)
