### ISSUE TITLE
-include flag yields FATAL error

### ISSUE THREAD

**Issue by JustSid** [CoatiSoftware/SourcetrailBugTracker#407]
I have the following compiler flag set on macOS `-include source_code/core/types/hl_types.h`, all project files work fine but I get the following FATAL error regardless: 

> FATAL ''source_code/core/types/hl_types.h'' file not found in /Applications/Sourcetrail.app/Contents/Resources/built-in

It says NO in the Indexed column. Putting in an absolute path results in the same error. It looks like the project indexed successfully though, at least from what I can tell.

**Comment by egraether** [comment]
Why do you need this `-include` flag? What happens if you just remove it?

**Comment by JustSid** [comment]
Well, the code doesn't compile anymore... It's a cheap way to force include a header similar (but more costly) to a prefix header file.

**Comment by egraether** [comment]
I see, so this file is always included.

I just tested myself and could reproduce it. I saw there was a leading space character in the error message so I tried a couple things. It works for me now with both absolute and relative paths if I omit the space character like this: `-includesource_code/core/types/hl_types.h`

Can you please try that?

This still seems a bit odd, please leave this bug open, I want to investigate further.

**Comment by JustSid** [comment]
Thanks for looking into this! I tried it without the space, I still receive the same error about the builtin file. Actually, I'm surprised it works without the space and the compiler isn't complaining about it.

**Comment by egraether** [comment]
The file path has to be relative to the source file for me, so you probably need to use an absolute path since all source files might not be in the same directory. Did you try with absolute path again and without space again?

**Comment by mlangkabel** [comment]
We just re-tested this and it's working fine. The restrictions are:
* either use an absolute path for the forced include
* or use a path that is relative to one of the provided header search paths (added with `-isystem`)
