### ISSUE TITLE
Maven import shows no source files

### ISSUE THREAD

**Issue by ochaloup** [CoatiSoftware/SourcetrailBugTracker#428]
I hit troubles to get imported some of the maven projects. Particularly I would like to import WildFly (https://github.com/wildfly/wildfly) but the maven import shows no source files being found. Setting whole class path by hand with "Empty Java Source Group" is painful. Is that something to do for get such a maven project being imported fine?

**Comment by mlangkabel** [comment]
Awesome! Thanks @ochaloup for reporting this one AND providing an example project. With that project I have been able to reproduce your issue. I'll look into it as soon as possible.

Adding the jars for the classpath by hand can be painful, I know. But you can just export them to a folder using the `mvn dependency:copy-dependencies` command, `ctrl` + `a` them and drag'n'drop them into the Sourcetrail Classpath listbox. Hope this helps for now :)

**Comment by ochaloup** [comment]
@mlangkabel great, thank you. The tip with the `mvn dependency:copy-dependencies` works quite satisfactory. I didn't know about this plugin. Now I can happily start to really experiment with the Sourcetrail. By me a really interesting project, thank you. 

I forgot to backping the question https://github.com/CoatiSoftware/SourcetrailBugTracker/issues/403 where the similar issue is discussed.

**Comment by mlangkabel** [comment]
fixed with Sourcetrail version 2017.2.44
