### ISSUE TITLE
The entered license key is malformed

### ISSUE THREAD

**Issue by egberts** [CoatiSoftware/SourcetrailBugTracker#434]
platform version:  CentOS 6.8, guest VMware

Sourcetrail version: 2017 2.0

Description:
The Enter License dialog box reported that the license sent by Coati and received using Microsoft Office 365 has been "malformed".

Steps taken:
* obtained a license from Coati.Io via Microsoft Office 365.   
* Saved the attachment using "Commercial Single User License copy.txt" filename.
* Executed 'scp Commercial\ Single\ User\ License\ copy.txt" testuser@192.168.1.15:/tmp/', using a Mac OS Terminal bash shell

Then over to the CentOS 6.8 VM (hosted by VMware Workstation), steps taken in 1st terminal:
* Executed vi /tmp/Commercial* using Gnome terminal
* Cut and paste entire license
* Pressed Control-Shift-C to copy

Then in the 2nd terminal (also in CentOS 6.8 VM)
* cd /opt/Sourcetrail
* ./sourcetrail.sh
* In a startup dialog box showing "Open Project" and "Unlock" button, clicked "Unlock"
* In a new dialog box showing "Enter License", pressed Control-V to paste license
* Red-lettered sentence appeared saying "The entered license key is malformed"

Of course, I'm not including the license here, but reporting it here in case there are others who shared the same plight.
as

**Comment by egberts** [comment]
Hexdump of the license shows that Unix single line-feeds (0x0a, \n) are used in the license file.  No carriage-return (0xd, \r) character were used.

Other observation with hexdump is that the last line does not have a line-feed.

**Comment by egberts** [comment]
Just downloaded, installed and retested the same license against Sourcetrail whose tarball version is  0_12_25 (yet still reports 2017 2.0 in 'About Sourcetrail').

Same red-lettered malformed error message.

**Comment by egberts** [comment]
UPDATE:   This is an issue with me attempting to re-use an OLD license key.

To upgrade your license key, visit https://www.sourcetrail.com/upgrade for more details on how to get a new license key.

Closing this issue.

**Comment by egraether** [comment]
Thank you! I was about to write the same.
