### ISSUE TITLE
Ability to use Visual Studio Plugin to navigate to symbol in Sourcetrail

### ISSUE THREAD

**Issue by macjohnmcc** [CoatiSoftware/SourcetrailBugTracker#436]
I'd like to be able to right click on a symbol (class, variable etc) in Visual Studio and select Set Sourcetrail cursor equivalent to the opposite Set IDE Cursor.

**Comment by mlangkabel** [comment]
Hi John, thanks for asking.
There should already be an option for that. If you have the Sourcetrail Exension for Visual Studio installed you should be able to right-click any symbol in your sourcecode and find an option called `Set Active Token` (with a little Sourcetrail icon next to it) in the context menu. I think that's the option you are looking for.

**Comment by macjohnmcc** [comment]
I will check thanks. I have about 6-8 extensions installed beyond
sourcetrail and about half of them add many righ5 click menus and sub
menus. Probably lost in the noise.
