### ISSUE TITLE
Compile definitions not taken from compile database

### ISSUE THREAD

**Issue by Ozaq** [CoatiSoftware/SourcetrailBugTracker#443]
I have a project with several libs that use different compile flags each.

The compilation database contains all compile flags but it looks like they are not read and I cannot specify different mutually exclusive flags for different source files.

Please take all compile flags from the compilation database.

**Comment by egraether** [comment]
@Ozaq Can you please send us your compilation database file and tell us which compile flags are not read?

Send to mail@sourcetrail.com if you prefer this to be off the public record.

**Comment by egraether** [comment]
This was related to #444
