### ISSUE TITLE
Indexation speed for large projects is very slow

### ISSUE THREAD

**Issue by phax** [CoatiSoftware/SourcetrailBugTracker#445]
Windows 64 Bit, 2017/3, default setup

1437/3980 files at 14:40
1446/3980 files at 14:47 ==> so 9 (average size) files in 7 minutes
Update:
1452/3980 files at 14:52 - stopping now :)

DB has 90 MB, memory consumption at 4,6 GB, CPU consistenly at 100%
All Maven based Java 8 projects

While writing this issue: no file added :(

**Comment by mlangkabel** [comment]
Hi @phax, thanks for reaching out to us!

To me that sounds a lot like the garbage collector is running a lot more than it is supposed to. Can you tell what's the maximum heap space for the JVM that gets instantiated by Sourcetrail? And how much memory is actually used while Sourcetrail is so slow? 

I recently discovered [VisualVM](https://visualvm.github.io/) which is a great tool to display this kind of info!

**Comment by phax** [comment]
@mlangkabel According to Process Explorer 4.6 GB of RAM was used. I didn't alter any of the default settings. Oracle JDK 1.8.0_131 64 Bit.

VisualVM can only monitor Java processes - SourceTrail seems to be a QT C++ encrypted application.... At least SourceTrail does not show up in the VisualVM process list (whereas e.g. Eclipse.exe does)

**Comment by phax** [comment]
Additional suggestions: add a "Stop" button in the "Maven Exporting Dependencies" and "Maven Generating Source Files" windows???
Maybe you can even ask the user if something changed... - whether this step can be skipped???

**Comment by mlangkabel** [comment]
Sourcetrail is indeed a C++ application but starts a JVM for the purpose of indexing a Java project. I think it's called `Local Application` in VisualVM.

Could you try to index your project with the previous release (Sourcetrail 2017.2.0)? We did some changes to the caching in 2017.3, maybe that's causing you trouble.

The pre-indexing tasks for a Maven projects are atomic, but stopping after one of them has finished and the other one started should be possible. Good suggestion, I opened #446.

And your last suggestion is even better! We don't even have to ask the user if something has changed but can store the currently known state in the Sourcetrail project and just compare to that! I opened #447.

**Comment by phax** [comment]
Feedback on 2017.2 next week

**Comment by LouisStAmour** [comment]
I've discovered some impossibly slow Java use cases myself -- I tried running Sourcetrail on some JSP files that were compiled to .java, and two things seem to occur. The first, it takes forever. The second, I'll see 0/1074 files or 1/1074 files in the Indexing Files window, but I'll see [4/1074] or [5/1074] in the status bar. Are the different counts a bug or an indicator of how many are successful (blue modal window) vs done + in-progress (status bar)?

**Comment by LouisStAmour** [comment]
Ah, I managed to speed it up by giving it lots more RAM and reducing the number of running index threads from 4 to 2. It was stuck at the 2GB mark, but managed to work with 3.5G of RAM over two threads. Also upgraded the JVM, but I don't think that did much.

**Comment by LouisStAmour** [comment]
Before:
![2017-08-30_22-30-40](https://user-images.githubusercontent.com/53444/29903869-236959b0-8dd4-11e7-81d1-5a80f83a9b63.png)

After:
![2017-08-30_22-39-47](https://user-images.githubusercontent.com/53444/29903880-2e7c848a-8dd4-11e7-9910-f3e0d7555c6d.png)

**Comment by LouisStAmour** [comment]
For those wondering how Sourcetrail handles JSP .java files, the answer is - not that well. Frankly, to get the most benefit from .java files, you'd have to match up variables to the comment lines in the corresponding JSP files. And well, given that some JSP directives, like `<%@ include file="..." %>` are completely undetectable from the .java side (I just checked, no comments or anything...) So you'd perhaps want to both scan the JSP and `.java` files to properly support JSP in this kind of an app, or fork/re-use Jasper, plus some kind of EL library to support `org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate` since the evaluation of EL strings appears to occur at runtime.

**Comment by mlangkabel** [comment]
That's a lot of feedback, thank you @LouisStAmour!

As you already guessed, the indexing window displays the amount of files already indexed while the status bar shows that's currently in progress.

We also noticed the issue of the Java indexer getting very slow once the heap is full. Right now we are testing a very different implementation of indexing Java files which looks very promising (in terms of both, indexing speed and coverage)!

JSP files use a different language than simple Java files. They contain a mixture of HTML and Java, so a pure Java parser that only knows the language specification of Java can't make sense of those files. I opened a language request for this one at #452.

**Comment by mlangkabel** [comment]
**Update**: @phax @LouisStAmour We just release Sourcetrail 2017.3.48 featuring the different Java indexing implemenation I was talking about last week! This release improves indexer coverage, indexing speed and indexing memory footprint! If I don't hear any complaints I will close this issue in a couple of days :)

**Comment by phax** [comment]
Reindex started at 14:05
Maven processing finished at 14:10
Full update started
Liked the "stop" button 👍 
14:14 - 29% - looks pretty linear so far

**Comment by mlangkabel** [comment]
Thanks for the quick reply! Happy to hear that the speed issue is gone now!
