### ISSUE TITLE
Local variable searching

### ISSUE THREAD

**Issue by hardenedapple** [CoatiSoftware/SourcetrailBugTracker#453]
I'm currently trying to understand some very large functions, and often have to search for where a local variable is declared and used.

The current behaviour of highlighting all references to a local symbol is nice, but I still have to scroll around and look carefully to find the declaration or other uses off-screen.

For distinguishing the first use, I'd suggest either the ability to jump to the declaration of a local symbol (like vim's `gd` or `1gd`), or a different highlight colour (once clicked) for declaration.

To make finding uses slightly easier (which I think would be less useful than helping to get the declaration, but still quite nice) I'd guess either a tooltip where you can select from the uses of that symbol in the current function (similar to an emacs `occur` with the buffer narrowed to the function), or an alt-rightclick jumps to the next occurance while ctrl-rightclick jumps to the previous occurance (similar to what the acme editor does on right-click by default).

**Comment by egraether** [comment]
Yes, I have that use-case too sometimes. Thank you for the suggestion!

**Comment by egraether** [comment]
Implemented with 2018.2.117
Show on-demand local reference count and navigation in the code view navigation bar.
