### ISSUE TITLE
Add option to hide anonymous namespaces

### ISSUE THREAD

**Issue by deepankarsharma** [CoatiSoftware/SourcetrailBugTracker#465]
Hide anonymous namespaces from namespace view.

**Comment by egraether** [comment]
Anonymous namespaces already get bundled together in the namespace overview. Do you still see lots of them at once?

**Comment by deepankarsharma** [comment]
<img width="492" alt="screen shot 2017-10-07 at 12 13 44 pm" src="https://user-images.githubusercontent.com/840385/31309723-0604236c-ab59-11e7-8098-9d1e4d90f973.png">

**Comment by egraether** [comment]
Oh, I see, nested anonymous namespaces. Didn't think about that. I will bundle them as well.

**Comment by egraether** [comment]
Fixed with 2017.3.77

Nested anonymous namespaces get also bundled into anonymous namespaces now
