### ISSUE TITLE
Errors in QtCreator Plugin

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#467]
Produces following errors on launch after copying libSourcetrail.dylib in the PlugIns folder:
```
Those folders contain errors and cannot be loaded:
"Unable to resolve dependency: Core (4.2.0)"
"Unable to resolve dependency: CppEdit (4.2.0)"
```

**Comment by st4ll1** [comment]
The reason for is that the plugin version differs from the Qt Creator version.

The mentioned plugin is build for Qt Creator version 4.2.x

On [Github Releases](https://github.com/CoatiSoftware/qtc-sourcetrail/releases) there are builds available for Qt Creator 4.2.x, 4.3,x and 4.4.x
make sure to download the right one.
