### ISSUE TITLE
Cannot handle large source file

### ISSUE THREAD

**Issue by rivenhk** [CoatiSoftware/SourcetrailBugTracker#469]
It seems that the tool cannot handle with large source files like source code from The SQLite Amalgamation. The program just hangs when i try to use features like adjust graph depth.

Sourcetrail version: 2017.3.48 - windows 64bit

**Comment by egraether** [comment]
The call graph can take some time processing when using a high depth. The time increase with each step is not linear, because the number of nodes to process is not. But it also really depends on the codebase.

What else is slow?

**Comment by egraether** [comment]
Main issue seems to be, that no visible loading animation is shown when processing takes long
+1 for #148
