### ISSUE TITLE
ERROR: boost::interprocess::bad_alloc

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#471]
Hello,

I'm trying to index a large project (~3k compilation units), getting the following error as soon as I start indexing:

```
11:14:50 | SqliteDatabaseIndex.cpp:19 createOnDatabase() | INFO: Creating database index "component_access_node_id_index"
11:14:50 | InterprocessIndexerCommandManager.cpp:38 setIndexerCommands() | INFO: grow memory - est: 83444906 size: 1048576 free: 1048352 alloc: 82396554
11:14:50 | InterprocessIndexerCommandManager.cpp:42 setIndexerCommands() | INFO: growing memory succeeded
11:14:51 | TaskRunner.cpp:30 update() | ERROR: boost::interprocess::bad_alloc
11:14:51 | INFO: send MessageStatus An unknown exception was thrown during indexing. - error
```

Suggestions?

**Comment by egraether** [comment]
Thank you for reporting this! It's an issue when writing the compile commands into shared memory. The allocation succeeds, but then it throws an exception on writing. The allocated memory is probably too small for some reason.

Can you please upload your compilation database file so we can try to reproduce this? You can also send via mail to support@sourcetrail.com or share it with us otherwise.

**Comment by egraether** [comment]
Thanks for the file. Could not reproduce on macOS, will try on Linux.

**Comment by TTimo** [comment]
Yeah this is on Linux, I haven't tried on any other platforms.

**Comment by egraether** [comment]
Can't reproduce on Linux either. I get the same shared memory size estimation on both Mac and Linux, which is sufficiently big:

```
13:51:40 | 0x700009019000 | InterprocessIndexerCommandManager.cpp:38 setIndexerCommands() | INFO: grow memory - est: 113407662 size: 1048576 free: 1048304 alloc: 112359358
13:51:40 | 0x700009019000 | InterprocessIndexerCommandManager.cpp:42 setIndexerCommands() | INFO: growing memory succeeded
13:51:41 | 0x700009019000 | InterprocessIndexerCommandManager.cpp:59 setIndexerCommands() | INFO: srctrlmem_icmd_f09c3033-32d5 - size: 113407934 free: 32997486 used: 80410448 pct: 71
```

@TTimo Can you please share some information about your machine? Operating system, architecture

**Comment by TTimo** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

Linux icarus 4.13.0-041300-generic #201709031731 SMP Sun Sep 3 21:33:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
16GB RAM

**Comment by TTimo** [comment]
I removed files until the indexing would start. At 600 the indexing starts without crashing, and it does at 750.

The default of 8 indexer threads running fills up my 16GB of RAM within a minute or two, causes various OOM and aborts.

With 4 indexer threads I seem to be stable at around 12GB of RAM used, I'll leave it running to see if it survives the full indexing.

**Comment by egraether** [comment]
The OOM issue is most likely caused by indexing information piling up in memory, because the indexer processes are much faster than the thread saving to the database. 

Can you please send us a log file of a run where a OOM issue occurs?

**Comment by egraether** [comment]
With v2017.3.93 indexer processes get slowed down when database injection takes comparably longer, to avoid indexed information piling up and causing OOM. Also increased size estimation for indexer commands in shared memory, still needs proper exception handling though.

We will upload a beta build soon, I will let you know when it's ready.

**Comment by egraether** [comment]
Fixed wrong datatype usage for string size estimation with v2017.4.0

@TTimo Please test with our new [beta release](https://www.sourcetrail.com/downloads#beta).

**Comment by TTimo** [comment]
The bad_alloc error still happens in 2017.3.48

```
17:51:27 | SqliteDatabaseIndex.cpp:19 createOnDatabase() | INFO: Creating database index "component_access_node_id_index"
17:51:27 | InterprocessIndexerCommandManager.cpp:38 setIndexerCommands() | INFO: grow memory - est: 166609684 size: 1048576 free: 1048352 alloc: 165561332
17:51:27 | InterprocessIndexerCommandManager.cpp:42 setIndexerCommands() | INFO: growing memory succeeded
17:51:28 | TaskRunner.cpp:30 update() | ERROR: boost::interprocess::bad_alloc
17:51:28 | INFO: send MessageStatus An unknown exception was thrown during indexing. - error
17:51:28 | StatusBarController.cpp:79 setStatus() | INFO: STATUS An unknown exception was thrown during indexing.
```

**Comment by egraether** [comment]
Please try the beta release [2017.4.0](https://www.sourcetrail.com/downloads#beta)

**Comment by TTimo** [comment]
Ah, I was downloading the wrong build. The bad_alloc exception is gone, the indexer is running on 8 threads and has gone through 50 files so far without maxing out the memory .. I'll let it run through the whole process but this is looking very good!

**Comment by TTimo** [comment]
4h20mn indexing .. success!
