### ISSUE TITLE
Hide specific nodes and edges from the graph with context menu action

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#472]

**Comment by egraether** [comment]
+1 by mail

**Comment by xueyayang** [comment]
+1. I need this too. 
And showing  inheritance in a new window will also be good, I mean, like Xmind, multiple sheets view.

**Comment by egraether** [comment]
Implemented with 2017.4.71
Hide nodes and edges via context menu action or `Alt + Click`
