### ISSUE TITLE
Exclude files from indexed by wildcard / regex

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#475]

**Comment by jdseyl** [comment]
+1

**Comment by herrjakob** [comment]
I would also find this extremely helpful in order to speed up the work on a relatively large code base (1.200.000 loc without unit tests).

**Comment by mlangkabel** [comment]
Added wildcard support for new release. Sourcetrail version 2018.1.98 describes these wildcards as follows:
* You can use the wildcard "\*" which represents characters except "\\" or "/" (e.g. "src/\*/test.h" matches "src/app/test.h" but does not match "src/app/widget/test.h" or "src/test.h")
* You can use the wildcard "\*\*" which represents arbitrary characters (e.g. "src\*\*test.h" matches "src/app/test.h" as well as "src/app/widget/test.h" or "src/test.h")

**Comment by Kochise** [comment]
But it doesn't work. I'd like to exclude all '/test/' folders from analysis, regardless of their location, so I added '\*\*/test/\*\*' in the "Excluded Files & Directories" but the indexer stills fetch the source files inside the '/test/' folders.

**Comment by egraether** [comment]
Just tested this and couldn't find an issue.

Which language and which Source Group type are you using?
Is there anything odd about your file structure e.g. symbolic links, case-sensitivity?
