### ISSUE TITLE
Template class methods not shown

### ISSUE THREAD

**Issue by Red-Portal** [CoatiSoftware/SourcetrailBugTracker#491]
![image](https://user-images.githubusercontent.com/18320033/31939212-9d676d24-b8f4-11e7-85c3-6b60314b787f.png)

Is this normal behavior?

**Comment by mlangkabel** [comment]
HI @Red-Portal, thanks for asking. It appears that you found a really interesting bug here. We didn't see much from your screenshot but after tinkering a little but we managed to reproduce the issue. It looks like you have that template class forward declared at some other location in your source code and that this forward declaration uses different names for its template parameters!

**Comment by Red-Portal** [comment]
Oh I'll fix that. I'll let you know afterwards

**Comment by Red-Portal** [comment]
![image](https://user-images.githubusercontent.com/18320033/31942645-f59936b0-b900-11e7-9a74-df083c646d79.png)

Yeah the name mismatch was the reason.
Works like a charm now!

**Comment by mlangkabel** [comment]
Thanks for keeping us informed of your progress! However, a template class definition and its forward declaration should share the same node, even if the template parameters have different names. So I created another issue (#492) to our track the progress here.
