### ISSUE TITLE
don't force fully reindexing on settings change

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#493]
Feature request..

I added an include path to fix a handful of files that couldn't find a header. I don't want to be forced to fully reindex (a 4h process).

See: [![Screenshot from Gyazo](https://gyazo.com/705525f02027e278640319198b468a7f/raw)](https://gyazo.com/705525f02027e278640319198b468a7f)

**Comment by egraether** [comment]
I see, we could remove this message box. But you still need to refresh those files that couldn't find a header, to get rid of the errors. How do you do that?

**Comment by TTimo** [comment]
Well there's only 18 files out of 4k that had a fatal error .. so I guess the 'refresh' in Sourcetrail would be retrying those?

**Comment by egraether** [comment]
We currently don't have an option to refresh only files with errors (incomplete files), but it would make sense to add this option. I opened #496 for that. Until that is implemented, we keep the force refresh on settings change.

**Comment by egraether** [comment]
Implemented with 2017.4.83
