### ISSUE TITLE
Sourcetrail.sh lacks a #!/bin/bash first line

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#495]
2017.4.20 linux x86_64

The Sourcetrail.sh script is executable in the tar archive, but lacks a first line with a shell interpreter (typically `#!/bin/bash`). So it can't be started from the command line.

**Comment by egraether** [comment]
Oh, thanks for letting us know. Apparently not every Linux distro has a problem with that, at least not the one's we tested on. I'm already building a new package.

**Comment by TTimo** [comment]
I suppose GUI file explorers (like nautilus) may not have a problem with this and rely on the .sh extension to pass the script to a shell for startup.

**Comment by egraether** [comment]
Fixed with 2017.4.21

New downloads for Linux are up: https://www.sourcetrail.com/downloads
