### ISSUE TITLE
Source code window has no horizontal scrollbar

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#498]
linux x86_64

The source code window lacks a horizontal scrollbar. I have to widen the window sometimes with long lines of code..

**Comment by mlangkabel** [comment]
This is an issue on all platforms. The horizontal scrollbar as well as the file's title are part of the code snippet and may vertically be scrolled out of sight.

**Comment by egraether** [comment]
This is a duplicate of #432 
We get this feedback a lot lately, so it has become a priority for the next release to fix this.
