### ISSUE TITLE
Add option for source file encoding to application settings

### ISSUE THREAD

**Issue by xueyayang** [CoatiSoftware/SourcetrailBugTracker#500]
Version 2017.4.20 - 32 bit
Openning a cpp source file  contains Chinese character（汉字），mainly comments，it displays wrong.
Is these a setting option to change the encoding of code window?

**Comment by mlangkabel** [comment]
I think I managed to reproduce your issue by choosing the "Traditional Chinese" encoding to save the source file.

However, Sourcetrail is able to display these characters correctly 
if the source file is encoded with "UTF-8 without BOM"

![chinese_characters](https://user-images.githubusercontent.com/16242920/32114779-a4616614-bb44-11e7-80f5-09b97bb88216.png)

**Comment by mlangkabel** [comment]
Even though C++ doesn't allow any Chinese characters in code they can still be present in the comments. And since we shouldn't force every user to use UTF-8 to save their source files, we probably need to offer an option to pick the appropriate file encoding.

**Comment by xueyayang** [comment]
Yes my source code is encoded with GBK2312，the default choosing of a chinese version visual studio on a chinese version windows·

Thx for your replying. Excellent Sofeware! I have used it about a week, it’s amazing. U guys are doing great work!

**Comment by mlangkabel** [comment]
Implemented with Sourcetrail 2017.4.27

**Comment by xueyayang** [comment]
> Implemented with Sourcetrail 2017.4.27

When do i can download this version?

**Comment by egraether** [comment]
It's available now as 2017.4.46: https://www.sourcetrail.com/downloads
