### ISSUE TITLE
Sourcetrail report 0 references on a C++ method with multiple references

### ISSUE THREAD

**Issue by pron** [CoatiSoftware/SourcetrailBugTracker#503]
Platform: macOS 10.3
Sourcetrail Version:  2017.4.20 - 64 bit

Analyzing OpenJDK's HotSpot code (no errors reported) Sourcetrail reports 0 references from some C++ methods that do have references, even in the same file. References to the methods are not highlighted in the code view when I hover over them.

**Comment by egraether** [comment]
Can you provide a screenshot please? (send to support@sourcetrail.com for confidentiality)

**Comment by pron** [comment]
Sent.
