### ISSUE TITLE
Sourcetrail crashes on startup with no rights to create shared memory

### ISSUE THREAD

**Issue by ruipires** [CoatiSoftware/SourcetrailBugTracker#508]
Versions newer than Sourcetrail 0.11.86 crash in my system (Windows 7) on startup with no useful error message.

Only a generic windows crash dialog pops up stating "Sourcetrail.exe has stopped working".

Unsure how to track down the root cause.

**Comment by mlangkabel** [comment]
Hi @ruipires, thanks for contacting us. This is indeed a strange issue which we cannot reproduce. Please try the following steps and tell us if this resolved your issue.
* Uninstall your current install of Sourcetrail and check if the entire Sourcetrail install folder has been removed. If not, remove it manually.
* Furthermore, remove the user data folder that Sourcetrail creates. It is located at `C:\Users\YourUserName\AppData\Local\Coati Software`.
* Install a more recent version of Sourcetrail and run it.

**Comment by ruipires** [comment]
Hi @mlangkabel, thanks for the reply.
I retried, following you instructions.
Sourcetrail_0_12_25_64bit fails in the same way.
My first try was with the latest version (Sourcetrail_2017_4_20_Windows_64bit), and I had never installed Sourcetrail before.

**Comment by mlangkabel** [comment]
Ok, can you please provide us with a log file for one of your unsuccessfull Sourcetrail runs? You can either post it here or send it via mail to mail@coati.io if you don't want to post it publically.

I'm aware that you cannot enable logging using the UI so you need to open the `ApplicationSettings.xml` file located in `C:\Users\YourUserName\AppData\Local\Coati Software\Sourcetrail 64-bit` and edit it manually.

To enable logging, add the following node to the xml tree:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<config>
    <application>
        <logging_enabled>1</logging_enabled>
    </application>
</config>
```

After making this edit, please let Sourcetrail run into the crash again. Your log file will be generated at  `C:\Users\YourUserName\AppData\Local\Coati Software\Sourcetrail 64-bit\log`

**Comment by ruipires** [comment]
Hi,

The log for Sourcetrail_2017_4_20_Windows_64bit is : 

> 09:50:41 | 3264 | LogManager.cpp:40 LogManager::setLoggingEnabled() | INFO: Enabled logging for Sourcetrail 64 bit, version 2017.4.20
> 09:50:41 | 3264 | SharedMemory.cpp:123 SharedMemory::SharedMemory() | ERROR: boost exception thrown at shared momory creation - srctrlmem_grbg_cllctr_64: Access is denied.
>

**Comment by egraether** [comment]
Thank you for the log information. For some reason the shared memory allocation fails with "Access is denied".

Which operating system version are you using?
Are you running Sourcetrail on a machine with restricted rights?
Did you try running Sourcetrail as admin?

**Comment by ruipires** [comment]
I am running it on Windows 7 Enterprise.
The machine has restricted rights, but running as admin allows it to startup (wasn't expecting this one).

**Comment by egraether** [comment]
Thank you for your info! We need to handle this case more gracefully.

**Comment by ruipires** [comment]
Thanks!

Wondering if this could be made to work with no admin rights, like it was in version 0.11.86.
Nonetheless, handling the case in a more user friendly way will certainly help other users that bump into the same issue.

**Comment by egraether** [comment]
With Sourcetrail 0.12 we switched to multi process indexing with shared memory for better stability. You are the first we know about with this issue.

More userfriendly with 2017.4.35
Don't crash on application launch. Show message box with infos when trying to index a project.
