### ISSUE TITLE
Support Python

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#51]
starting point: https://docs.python.org/3.5/library/ast.html

**Comment by term-inal** [comment]
you can also start with gast: [https://github.com/serge-sans-paille/gast](https://github.com/serge-sans-paille/gast)
It uses standard ast module from python but support many python versions (and syntax specificities in one module)

**Comment by mlangkabel** [comment]
@term-inal Thanks for pointing us there! Getting some AST info for Python code will be surely the first step once we start tackeling that language. 
After that the next (and probably most complicated) step will be getting some kind of type information on all the objects used in the code that should be indexed.

**Comment by egraether** [comment]
+1 by mail

**Comment by schmotzle** [comment]
+1

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Might be helpful: https://tomassetti.me/parsing-in-python/?utm_content=buffer70936&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by egraether** [comment]
+1 by mail

**Comment by D1mon** [comment]
+1

**Comment by brianly** [comment]
Adding my voice as someone who'd find this valuable and be able to buy the product for work.

**Comment by egraether** [comment]
+1 by mail

**Comment by cnjsdfcy** [comment]
+1

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
We created the [SourcetrailDB](https://github.com/CoatiSoftware/SourcetrailDB) library to allow anyone to write custom indexers and extend language support for Sourcetrail.

And as next language we started working on a [Sourcetrail Python indexer](https://github.com/CoatiSoftware/SourcetrailPythonIndexer) using jedi and SourcetrailDB. It's only an early prototype right now, but it looks promising. I will post updates here. Please let us know if you want to get involved!

**Comment by dmoody256** [comment]
+1

**Comment by egraether** [comment]
Added Python Support with 2019.2.0 based on [SourcetrailPythonIndexer](https://github.com/CoatiSoftware/SourcetrailPythonIndexer)
For bugs and feature requests please open issues on that repo.
