### ISSUE TITLE
Static Functions in separate C Modules are merged

### ISSUE THREAD

**Issue by jdseyl** [CoatiSoftware/SourcetrailBugTracker#515]
If two separate modules contain two separate static functions that are named the same, then Sourcetrail incorrectly merges them into a single symbol.  This is similar to issue #514, but with functions and not variables.

**Comment by mlangkabel** [comment]
@jdseyl, thanks for pointing this out! 

Just to clarify for other readers: "Module" == "Translation Unit"

**Comment by mlangkabel** [comment]
Fixed with Sourcetrail 2017.4.48
