### ISSUE TITLE
Cannot choose files from files and directories dialog

### ISSUE THREAD

**Issue by fedepell** [CoatiSoftware/SourcetrailBugTracker#521]
In many cases there are dialogs that are supposed to be able to choose both a file or a directory. For example when creating or editing a project and creating a source group for C++ there is "Excluded files or directories" or for Java "Class Path". 
The user, and the online help, should be able to choose either a directory or a file, but the "Files of type" filter is always and only "Directories".

Adding the single files without the dialog box but with the direct text manipulation (clicking the pencil icon giving "edit plain text") will allow adding files and correctly use them. So it's just a matter of the File Dialog filtering.

To reproduce just create a new project and try one of the mentioned filters in the source groups.

![strail2](https://user-images.githubusercontent.com/19709142/32828484-7a09000c-c9ef-11e7-8af4-0d5226e4f2b3.PNG)

![strail](https://user-images.githubusercontent.com/19709142/32828482-79d8a57e-c9ef-11e7-91e7-42eca290c1f4.PNG)

Sourcetrail Version: 2017.4.46 64-bit
OS Used: Linux
Distribution: CentOS 7.3 and Ubuntu 16.04

**Comment by mlangkabel** [comment]
can reproduce this with Sourcetrail 2017.4.46 on Windows 7

**Comment by egraether** [comment]
Thanks for reporting. As far as I remember this is a problem with the native FilePicker dialogs Qt uses, that only allow for picking either files or directories. Maybe there is a way of doing this now with a newer version, need to look into it.

**Note:** Both files and directories can also be added via drag&drop.

**Comment by mlangkabel** [comment]
fixed with Sourcetrail version 2017.4.101
