### ISSUE TITLE
Do not open terminal window on linux

### ISSUE THREAD

**Issue by AlexRevo** [CoatiSoftware/SourcetrailBugTracker#525]
Platform version: Ubuntu 16.04 LTS (64-bit).
Sourcetrail version: 2017.4.46.
Description of the problem: Running Sourcetrail on linux via Dock shortcut opens a terminal window that seems to be used to report errors and warnings. I do not want this window to be shown because it's of no use to me and is cluttering my screen.
Steps to reproduce the problem: Run Sourcetrail via dock or dash.

Things I tried to solve the issue myself:
1. The obvious: `ctrl+z` -> `bg` -> `disown`. The terminal window, however, ignores job control and just prints `^Z` instead of suspending.
2. Running via existing terminal window. Same as item 1, except it works. This is, however, too many steps to just run a program, in my opinion.
3. Editing `sourcetrail.desktop` setting `Terminal=false`. This works great, but will probably be reversed with every update. Also, the output is lost in this case, and, even though I don't want to see it most of the time, it might be needed for a bug report or something.

Proposed solution: Get rid of the terminal window and output to a log file instead.

**Comment by egraether** [comment]
Fixed with 2017.4.102
