### ISSUE TITLE
Remove selected text when pasting into search box

### ISSUE THREAD

**Issue by JaapAap** [CoatiSoftware/SourcetrailBugTracker#527]
Right now, pasting an expression into the search dialogue box (with previous search text selected) does leave the previous search text in place. I would much prefer to see 'standard windows behavior' here.

**Comment by egraether** [comment]
Yes, I noticed that too recently. Was introduced with the last release, where we convert search queries back to plain text on search field focus.

**Comment by egraether** [comment]
Fixed with 2017.4.92
