### ISSUE TITLE
Website Links don't work on iPhone X

### ISSUE THREAD

**Issue by geraldstangl** [CoatiSoftware/SourcetrailBugTracker#528]
Quite many links don't work on your website on iPhone X on iOS 11.2. For example the videos or the social media buttons. 
![img_e56a5f5cd1b9-1](https://user-images.githubusercontent.com/104761/33904599-541e74d8-df7c-11e7-9a1b-cff3b123da7e.jpeg)

**Comment by mlangkabel** [comment]
Wow, thanks for telling us! I've got the same issue if I just reduce the width of my browser window on my desktop pc. It looks like an invisible element covers the entire screen and blocks clicks at all the links.

**Comment by egraether** [comment]
Thanks for reporting! Same for Firefox on Mac OS. Notified the our web guy.

**Comment by egraether** [comment]
It's fixed now. Thanks for reporting!
