### ISSUE TITLE
Maven project finds 0 source files to index

### ISSUE THREAD

**Issue by photex** [CoatiSoftware/SourcetrailBugTracker#532]
Howdy! Just bought a license for 2017.4.46 and am disappointed that Sourcetrail doesn't find any sources to index on my maven project. There are no errors reported.

There are about 100 *.java files in `src/main/java` so this is a surprising result!

What steps can I take here. I don't really want to have to manually point sourcetrail to all my transitive dependencies.

**Comment by mlangkabel** [comment]
Hi @photex, thanks for reporting this issue.

It looks like a more recent release of the Maven help-plugin introduced a changed that handles projects that contain sub-projects (sub-folders with pom.xml files) different from project that do not contain any sub-projects. Sourcetrail has not yet caught up with this change and thus fails to handle projects that do not contain sub-projects. 

Please let us know if your project contains any sub-projects so we know that this is the issue you are talkig about.

**Comment by photex** [comment]
Hi @mlangkabel, this project had a flat layout as far as I can tell. You can close the issue if you like though because I now saw the tip to use the copy-dependencies trick to easily setup the classpath for the project.
Annotations via lombok aren't working but that's another story! :D

**Comment by mlangkabel** [comment]
Thanks for letting us know! I'll close this issue once we fixed the Maven project setup for projects that don't contain sub-projects.

**Comment by mlangkabel** [comment]
fixed with Sourcetrail 2017.4.134
