### ISSUE TITLE
Handling multiple matches more intuitively

### ISSUE THREAD

**Issue by kecsap** [CoatiSoftware/SourcetrailBugTracker#538]
Version: 2017.04.46
Platform: Ubuntu Xenial

1. Search for a variable
2. Multiple matches found inside a function
3. Clicking on the edge (line) in Search view, Code view will navigate for the first match.

Problem:
There is no any indication that there are multiple matches inside the same function.

Proposed solutions:
- Add a match count as a number to the edge in Search view if there are more matches than one.
- Mark with bold font style the currently selected function (the source of the edge in Search) in Code view
- Subsequent clicks on the same edge should move the focus in Code view to the later matches inside the same function (source of the edge).

**Comment by egraether** [comment]
This is a similar problem as #453 for local variables.

I agree that we should look into this.

**Comment by egraether** [comment]
Implemented with 2018.2.117
Show on-demand local reference count and navigation in code view navigation bar.
Subsequent clicks on the same edge also iterate forward.
