### ISSUE TITLE
Remember the image export path

### ISSUE THREAD

**Issue by GitGoogol** [CoatiSoftware/SourcetrailBugTracker#541]
When I do more image exports, I always again have to navigate to the path where I want to store the image.

**Comment by mlangkabel** [comment]
Oh, that sounds pretty annoying! What platform are you working on?

**Comment by GitGoogol** [comment]
I am working on Win7 Enterprise 64-bit.
I am using Sourcetrail 2017.4.46 - 64 bit.

**Comment by mlangkabel** [comment]
Thanks! We managed to reproduce the issue and fixed it with Sourcetrail 2018.1.9
