### ISSUE TITLE
error: cannot use ''throw'' with exceptions disabled

### ISSUE THREAD

**Issue by ywu** [CoatiSoftware/SourcetrailBugTracker#543]
I am using the latest version of sourcetrail on the latest version of MacOS. After indexing my C++ source code, I see several errors like the title of this issue. I'm new to sourcetrail, I don't understand why exceptions was disabled for me. I didn't do that, and I cannot find how to turn it on.

**Comment by mlangkabel** [comment]
Hi @ywu, thanks for letting us know! My first question to pinpoint the issue is: How did you set up your Sourcetrail project?

**Comment by ywu** [comment]
Thanks. I'm unsure exactly what you are looking for. My Sourcetrail project is a new project I just created using the Sourcetrail GUI. I looked at the clang-tool command, which is something like the following:
`
clang-tool -fno-delayed-template-parsing -fexceptions -c -w -ferror-limit=0 -isystem /Users/wu/Workspace/ -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -isystem /usr/local/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -isystem /usr/include -isystem /Users/wu/Workspace/mtest -std=c++17 /Users/wu/Workspace/mtest/src/closure.h`

Note the **`-fexceptions`** in the command. It should allow exceptions used in the C++ code. I don't understand why I still get the `cannot use ''throw'' with exceptions disabled` error.

**Comment by mlangkabel** [comment]
Thanks, that's exactly what I wanted to know. It would have been different if you had set up the project using an existing clang compilation database. So you did everything by yourself. 

As you already noticed we are adding the `-fexceptions` flag as default parameter to the clang tool. This should work for the regular case.

I just did some research and encountered this thread: http://clang-developers.42468.n3.nabble.com/cannot-use-throw-with-exceptions-disabled-td2963038.html

They suggest to use the `-fcxx-exceptions` flag. You can try that by adding this flag to the `Additional Compiler Flags` listbox in your Sourcetrail project settings.

Please let us know if that helped or if you found any other flag that you could add to get rid of this error.

**Comment by ywu** [comment]
The -fcxx-exceptions flag doesn't help, but your comment points me to playing around the complier flags. After some trials and errors, I found out that the -xc++ option works. This option explicitly states the language is C++. Thanks for your help.

**Comment by mlangkabel** [comment]
Awesome! Thanks for letting us know. We will investigate this flag. Maybe it's suitable to be part of the default flags Sourcetrail uses for indexing C++ code.
