### ISSUE TITLE
No IDE connected - Eclipse as IDE

### ISSUE THREAD

**Issue by nkolban** [CoatiSoftware/SourcetrailBugTracker#546]
I running sourcetail on Linux (Ubuntu 17.xx).  I have Eclipse Oxygen installed and Sourcetrail 2018-1.18 64 bit.

From Eclipse, I can right click in a C source file and select eSourceTrail -> Send Location to Coati and the source file shows up.  However I can't get the reverse working.  My goal is to find a source file in Sourcetrail and then open it in Eclipse.  At the bottom right of Sourcetail there is a message that reads "No IDE connected".

I'll be happy to capture/send any diagnostics requested or screen share as needed.

I am a licensed user.

**Comment by nkolban** [comment]
I thought to look in the Eclipse error log and find the following:

```
Message: Tcp server crashed
Stack trace:
org.eclipse.core.runtime.AssertionFailedException: null argument:The dialog should be created in UI thread
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.getSWTImage(IconAndMessageDialog.java:285)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.getErrorImage(IconAndMessageDialog.java:236)
	at org.eclipse.jface.dialogs.MessageDialog.init(MessageDialog.java:245)
	at org.eclipse.jface.dialogs.MessageDialog.<init>(MessageDialog.java:234)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:421)
	at org.eclipse.jface.dialogs.MessageDialog.openError(MessageDialog.java:520)
	at io.coati.eSourceTrail.core.TCPServerWorker.sendPing(TCPServerWorker.java:67)
	at io.coati.eSourceTrail.core.TCPServerWorker.run(TCPServerWorker.java:92)
```
![image](https://user-images.githubusercontent.com/3421732/35605723-33d7bab2-0610-11e8-8879-c17c7a08053d.png)

**Comment by nkolban** [comment]
I think I may have found a possible answer.

Looking at the netstat output, we see the ports bound to an IP address i.e. 127.0.0.1 as opposed to any addresss 0.0.0.0.   In my Eclipse coati configuration, I had specified the hostname of my PC which would resolve to 192.168.1.11 when I changed this to `localhost`, it started to work.

![image](https://user-images.githubusercontent.com/3421732/35605841-28bc349a-0611-11e8-8267-247817b76db0.png)

Is it possible that the code should be binding to any incoming network interface and not just 127.0.0.1?

**Comment by mlangkabel** [comment]
Hi @nkolban, thank you for telling us and also thank you for your investigation! I'm glad that you got it working.

You are right: changing the IP in the Eclipse plugin doesn't make much sense if the other side doesn't support this. Maybe we should just always use localhost without making this a configurable option, so no one can pick mismatching settings here. 

What do you think about that?

**Comment by nkolban** [comment]
Assuming that Sourcetrail and Eclipse should always be on the same desktop,  then it doesn't appear to make sense to allow the user to name the IP address targets so likely you would want to remove the entry from Eclipse.

You might always want to examine your Eclipse error handling too ... it looks like a network connection (from Eclipse) was attempted and failed ... which seemed to result in a dialog trying to be shown but Eclipse blocking that saying it wasn't a UI thread.

Also ... I'm a brand new user.  I understand this product used to be called "Coati" ... but is now Sourcetrail.  The name "Coati" still pervades in a confusing manner.  For example, Eclipse settings, menus etc.   I'd suggest taking the time to do be consistent across the board.

I evaluated for a week and realized this was EXACTLY what I wanted and bought a freelance developers license.    THANK YOU for making this.

**Comment by mlangkabel** [comment]
Those are all great remarks! Based on your comment I've created several issues on the [Eclipse Plugin issue tracker](https://github.com/CoatiSoftware/eSourcetrail/issues). Thank you very much!
