### ISSUE TITLE
Can I package for gentoo your software?

### ISSUE THREAD

**Issue by Petross404** [CoatiSoftware/SourcetrailBugTracker#549]
Sourcetrail would a great addition for gentoo portage tree under dev-util. All I ask is if I have the permission to make an ebuild for it and what it's license is. I have to state this in the ebuild to be accepted.

Thank you.

**Comment by egraether** [comment]
Hello! We are not sure how this will work, so I have a couple questions first.

Does the package need to get updated every time we release a new version?
Who would take care of the update?
We have our own [Software License](https://www.sourcetrail.com/terms-of-use) and it changes occasionally. Is it possible to provide a link or is text necessary?

**Comment by Petross404** [comment]
> Does the package need to get updated every time we release a new version?
Yes. At least, that's what I will try to do.

> Who would take care of the update?
Me, or anyone - else gentoo developer or user- that cares for the distro.

> We have our own Software License and it changes occasionally. Is it possible to provide a link or is text necessary?
Yes, but if a specific version doesn't change license, then it wouldn't have to change or be rechecked until an ebuild for the next version is to be written. If that's not the case, then I could append the stricter license that you would like and if you ever choose another one, sometime I will recheck it.

**Comment by mlangkabel** [comment]
Hi @Petross404, sorry for the delay. Our biggest concern was that we wouldn't be able to update the info you put out. We've been looking at the gentoo repo here on github and found the packages containing the manifest, ebuild and metadata files. So if we find that something needs to be updated we could just issue a pull request and that's it. So it's fine.

What I didn't find is where the actual binaries are stored. Can you tell us about the process of updating those?

**Comment by Petross404** [comment]
```
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

inherit eutils xdg qmake-utils

DESCRIPTION="Cross-platform source explorer for C/C++ and Java"
HOMEPAGE="https://www.sourcetrail.com"
IUSE=""

SRC_URI="
        x86?    ( "https://www.sourcetrail.com/downloads/${PV}/linux/32bit" -> "${P}"_x86.tar.gz )
        amd64?  ( "https://www.sourcetrail.com/downloads/${PV}/linux/64bit" -> "${P}"_x64.tar.gz )
"

KEYWORDS="~amd64 ~x86"
LICENSE=""
SLOT=0

DEPEND=""
RDEPEND="${DEPEND}"

S="${WORKDIR}/Sourcetrail"
RESTRICT="strip"
QA_PREBUILT="*"

src_prepare () {
        default

        cd setup/share/applications/
        sed -i \
                -e 's/\/usr\/bin\/sourcetrail/\/usr\/bin\/sourcetrail-bin/g' \
                -e 's/;IDE;Utilities;//' \
                sourcetrail.desktop || die

        eapply_user
}

src_install () {
        exeinto /opt/${PN}
        doexe   Sourcetrail sourcetrail_indexer Sourcetrail.sh || die

        exeinto /opt/${PN}/lib
        for i in $( ls lib/ | grep lib ); do
                doexe lib/$i || die
        done

        insinto /opt/${PN}
        doins -r data plugin user

        insinto /opt/${PN}/lib
        doins -r lib/platforms || die

        insinto /usr/share/applications
        doins   setup/share/applications/sourcetrail.desktop

        insinto /usr/share/icons
        doins -r setup/share/icons/
        newins  data/gui/icon/logo_1024_1024.png        sourcetrail.png
        newins  data/gui/icon/project_256_256.png       project-sourcetrail.png

        insinto /usr/mime/packages
        doins setup/share/mime/packages/sourcetrail-mime.xml

        make_wrapper ${PN} ./Sourcetrail.sh /opt/${PN}
}

pkg_postinst() {
        xdg_mimeinfo_database_update
        xdg_desktop_database_update
}

pkg_postrm() {
        xdg_mimeinfo_database_update
        xdg_desktop_database_update
}
```
SRC_URI defines from where the tarball will be downloaded. So each time I bump the ebuild's version ( `${PV}` ), portage automatically is redirected to the right path.

Let me know if there is something I am missing out. :)

**Comment by mlangkabel** [comment]
The `LICENSE` field is still empty. Can you please set this to "Sourcetrail EULA". The rest looks good to me. Feel free to add it to gentoo :)

**Comment by Petross404** [comment]
> Can you please set this to "Sourcetrail EULA

I will contact with some gentoo devs at irc to ask. Thank you very much!

PS You can close this issue, if anything comes up I will reopen it. :)

**Comment by Petross404** [comment]
Are there any obvious (runtime) dependencies besides those that are bundled? Except glibc, c++ library etc...

**Comment by mlangkabel** [comment]
For indexing C++ code:
* You need to have the standard headers on your machine. They usually come with a C++ compiler.

For indexing Java code:
* Java Runtime Environment (32bit Sourcetrail needs 32bit Java, 64bit Sourcetrail needs 64bit Java)
* If you want to import Maven projects, you need to have Maven on your machnie
