### ISSUE TITLE
Fortran Subroutine Call issue

### ISSUE THREAD

**Issue by sathishakula** [CoatiSoftware/SourcetrailBugTracker#552]
I have issue with a Fortran script and I'm really not good at understanding can you help me with the script.

![git](https://user-images.githubusercontent.com/20349676/36280202-24d7e5b8-125f-11e8-92c5-5271209ab674.png)

![image](https://user-images.githubusercontent.com/20349676/36280199-21205252-125f-11e8-8c4e-ea00b79b6fa2.png)

**Comment by egraether** [comment]
I'm sorry, but we are not familiar with Fortran, and our tool Sourcetrail doesn't support Fortran either.
