### ISSUE TITLE
IntelliJ plugin: no ide connected

### ISSUE THREAD

**Issue by wzguo** [CoatiSoftware/SourcetrailBugTracker#554]
在我本地使用sourcetrail时，右下角显示“no ide connected”，点击“show in IDE”，intellij ide中没有任何反应，idea中已经安装idea-sourcetrail插件，但是从idea中点击“send location”，sourcetrail可以接收到消息。我的环境：windows 7 +sourcetrail(version 2018.1.19-64 bit)+intellij ldea (2017.3.2)。
idea的端口配置如下图：
![snipaste_20180301_143158](https://user-images.githubusercontent.com/8574644/36830155-61822f88-1d5d-11e8-8900-ecf9205443df.png)
sourcetrail的配置如图：
![snipaste_20180301_143217](https://user-images.githubusercontent.com/8574644/36830160-679fd33e-1d5d-11e8-85a0-ddfb58bbb55f.png)

**Comment by egraether** [comment]
Please try changing the port numbers in both applications e.g. to 37292 & 37293

**Comment by wzguo** [comment]
@egraether 改完端口号后还是显示“no ide connected”，但是功能已经正常了，thank you.
