### ISSUE TITLE
Eclipse plugin: Seem to have to start Sourcetrail before Eclipse

### ISSUE THREAD

**Issue by nkolban** [CoatiSoftware/SourcetrailBugTracker#555]
Imagine I have my Eclipse environment already running.   I then start Sourcetrail and notice that the message at the bottom right says "No IDE Connected".   However, if I start Eclipse **after** Sourcetrail, I get the message "Connected to Eclipse".   I'm wondering if there a capability to tell Eclipse to "try again" to connect to Sourcetrail if I wish to start Sourcetrail after starting Eclipse?

**Comment by egraether** [comment]
Thanks for reporting, we will look into it!

**Comment by mlangkabel** [comment]
I haven't been able to reproduce the issue. Can you tell us which version of Sourcetrail and the Eclipse Plugin you use?

**Comment by nkolban** [comment]
Howdy ... Source Trail reports itself as 2018.0.18 (registered).

Eclipse is Oxygen (latest) and the plugin reports as:

eSourceTrail Feature 0.0.2.20170518-1329

**Comment by mlangkabel** [comment]
Hi @nkolban, thanks for your quick reply! I managed to reproduce the issue with an older version of the plugin but for me everything is working fine with the latest release: 0.0.2.20180202-1048

Can you please try to update to that version?

**Comment by mlangkabel** [comment]
@nkolban can you tell if this helped?

**Comment by nkolban** [comment]
Sorry ... I haven't had a chance to test yet.  I'll go ahead and close this issue out and put the onus on me to test again at that later release.  If it should show up then we can always re-open.  Thanks for the attention guys.  +++

**Comment by mlangkabel** [comment]
Sounds good!
