### ISSUE TITLE
incremental re-indexing is not 100% reliable

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#564]
(2018.1.19 - Linux 64 bit)

I was updating 'Additional Include Paths' in my project to fix a handful of fatal errors during indexing.
Every time I would tweak the 'Additional Include Paths' list, I would re-index 'Incomplete & Updated Files'.
After a while there were 0 files to re-index in the 'Incomplete & Update Files' list.
But there were still a handful of fatals in my Errors list, which wouldn't go away at that point.

After I did a full re-index, all these errors were gone however.

The Fatals were reported coming from 'non indexed files' - so maybe they just need to be cleared when doing a re-indexing?

**Comment by egraether** [comment]
The current issue is that we don't store include relationships for non-indexed files. So we don't know which errors in non-indexed files need to get cleared when only partly refreshing the project.

But we also need the full include hierarchy for similar other use-cases and this will be fixed then.

**Comment by TTimo** [comment]
Sounds good. Having access to the full include hierarchy on the user side would also help with fixing those issues in the first place.

**Comment by mlangkabel** [comment]
Fixed with Sourcetrail 2018.2.16
