### ISSUE TITLE
Cannot parse global external variable

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/SourcetrailBugTracker#565]
The following code snippet causes error 

> expected unqualified-id
> use of undeclared identifier ''foo''; did you mean ''for''?

```
#include <iostream>

extern "C" const int* __declspec(dllexport) volatile foo = nullptr;

int main()
{
	std::cout << foo << std::endl;

	return 0;
}
```

Code works fine in VS2015

**Comment by egraether** [comment]
Thanks for reporting, we will look into it!

**Comment by mlangkabel** [comment]
It looks like MSVC is a little bit more tolerant regarding position of the __declspec() attribute in the code. If you write it as `extern "C" __declspec(dllexport) const int* volatile foo = nullptr;` Sourcetrail (and the Clang compiler) will also accept the code.
