### ISSUE TITLE
Graph: wider hover popup window would be useful

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#570]
In the graph window, when I hover on some elements, the tool sometimes displays a popup window with information. For example, a full path of a file. 
The issue is that the width of this popup window is not wide enough to show the complete full path, only the beginning is shown and a scroll bar is added. This is annoying as I need to see part of the path not directly shown.
Currently this popup window seems to limit its width to about one third of my monitor width. This seems counter productive.
I would like Sourcetrail to have an option to make this window much wider and to show the complete full path directly (as much as possible).
Thanks
(I am using Version 2018.2.19-64 bit on Centos)

**Comment by egraether** [comment]
What if the file path was broken down into separate lines instead?

**Comment by pwillard2** [comment]
It would seem easier to allow for wider hover-popup windows, and other types of data would also benefit (not just file path).  I have seen class or method info in a hover-window with a scroll-bar for no real good reason.

**Comment by egraether** [comment]
Implemented with 2018.2.26
Allow tooltips to be as wide as the window.

**Comment by pwillard2** [comment]
that's was fast !! 
thanks.
