### ISSUE TITLE
Could not open default browser from ST

### ISSUE THREAD

**Issue by JoyIfBam5** [CoatiSoftware/SourcetrailBugTracker#584]
Distro: Fedora 28
On start, ST shows a dialog box saying that new version is available but when I click on a link in the dialog box nothing happens.
I see the following messages on a console.
```
XPCOMGlueLoad error for file /usr/lib64/firefox/libmozgtk.so:
/lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
Couldn't load XPCOM.
```

**Comment by egraether** [comment]
Thanks for reporting. This is a duplicate of #517
