### ISSUE TITLE
Auto-detect include paths exhausts available memory

### ISSUE THREAD

**Issue by davesteffen** [CoatiSoftware/SourcetrailBugTracker#585]
Hi -- large project (~1e7 sloc) , running 'auto detect' starts several processes which quickly grow to consume all available memory, at which point the machine stops being responsive.  Any ideas?

uname -a gives:
Linux picknik-3 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

The machine has 32 Gb ram

Thanks!

**Comment by egraether** [comment]
Thanks for reporting, we need to look into this.

How many directories did you add to the dialog "Detect Include Paths"? Did you only add relevant directories? If you add many large directories I can see why this is happening. Try to run the detection on one directory after the other.

**Comment by egraether** [comment]
Fixed with 2018.2.50
The detection algorithm got stuck in an endless loop under certain circumstances and that caused a boost::path::exception after sometime that crashed the application.
