### ISSUE TITLE
Sourcetrial typo in Update Check window

### ISSUE THREAD

**Issue by DCFerg** [CoatiSoftware/SourcetrailBugTracker#586]
Typo in the Update Check window:
![image](https://user-images.githubusercontent.com/13531298/40502870-45b2ce9a-5f5a-11e8-9b8d-4b918586bb55.png)
"Sourcetrial" should of course be Sourcetrail.

**Comment by egraether** [comment]
Thanks for reporting! Fixed with 2018.2.45

We do own [sourcetrial.com](http://sourcetrial.com) though, so we could potentially switch :)
