### ISSUE TITLE
Start indexing dialog not appearing

### ISSUE THREAD

**Issue by DaveC49** [CoatiSoftware/SourcetrailBugTracker#587]
When I first installed Sourcetrail ( on Linux Mint 18.3, Sourcetrail v 2018.2.36 - 64 bit, non-commercial ) a few days ago it initially indexed some C/C++ code without any problem with the Sourcetrail project created in the source directory. In the mean time I started to set up Eclipse and as I am using CMake with Eclipse and had to reorganise the code to include a build directory for out of source buildbs. When Sourcetrail initially indexed the code it wrote its files into the source code directory.  In reorganizing the code for Eclipse I decided I would prefer to put the Sourcetrail project files in the parent directory containing my source code directory as I will be using eGit and/or git back to a github repository. I deleted the original Sourcetrail project within Sourcetrail and then created a new project in the parent directory which contains the source directory and a build directopry and a local install directory. When I tried to do this, Sourcetrail would no longer index the code in the source directory and after setting up the project in the dialog, when I select Create it does not index the code and issues an error message in the Status bar and Status Window "Project could load any symbols because the index database is empty. Please re-index the project." I have totally uninstalled Sourcetrail and reinstalled it from scratch using the resetPreferences.sh to clear any preference settings before the uninstall, deleted the Sourcetrail <project>.srctrlprj, <project>.srctrlbm and <project>.srctrldb files from the parent directory, then installed Sourcetrail ( into /opt/sourcetrail  using sudo ./install,sh from a shell) again from the  original downloaded file and recreated the project with a different name, with exactly the same result. I have also tried using the cmake   -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE switch to regenerate my project files and the compile_commands.json file and tried recreating the project using that to set up the source group. ( again after deleting all Sourcetrail project files and resetting the Preferences). I have also tried recreating the Sourcetrail project in my source directory as I had done initially but this does not work either. Any suggestions?

**Comment by egraether** [comment]
So you could originally index your projects without problems, but now you can't index any projects anymore?

Can you index the sample project tictactoe?

Does your project still work if you create it within your source code directory?

When creating new projects, after filling in "Files and Directories to Index", click the "Show Files" button. Does it show any file paths?

What happens exactly when you click refresh? Does a dialog appear for selecting the refresh mode? Do you see the number of files that should be indexed?

**Comment by egraether** [comment]
Can you please:

* enable "Console and File Logging" in the preferences
* then try to create and index a project
* then send me the log file located in "Menu: Help -> Show Log Folder" (or if that doesn't work from ~/.config/sourcetrail/logs)

**Comment by egraether** [comment]
You can send it to support@sourcetrail.com

**Comment by DaveC49** [comment]
If I exit Sourcetrail and restart it I can index tictactoe.

My project doesn't work if I create it in the source directory, It gives the same error message.

If I create a new project and do show files after filling in the Files and Directories to Index I get a list of 168 files to index.
If I then try to index the project I get the same error message again. This is the Console file log from that session
[log_2018-06-02_22-08-47.txt](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/2064961/log_2018-06-02_22-08-47.txt)

This is the console file log from indexing tictactoe
[log_2018-06-02_19-10-31.txt](https://github.com/CoatiSoftware/SourcetrailBugTracker/files/2064964/log_2018-06-02_19-10-31.txt)

Sorry I was away fror a coupole of hours. 
Thanks David  (email davidcousens@bigpond.com)

**Comment by egraether** [comment]
The logs look alright. I think this is a UI problem. I think the start indexing dialog just does not show for you.

Do you have an uncommon display setup? Multiple screens? High-DPI screens?

Can you please open your project, then click refresh and take a screenshot?

**Comment by DaveC49** [comment]
I do have multiple screens on this computer and it does appear the indexing dialog is not showing up at all. I have checked that it is not appearing hidden on the other screen. This is the screenshot after opening the project and clicking on Edit->Refresh. I also tried the Full Refresh with no effect.
![screenshot from 2018-06-03 17-34-17](https://user-images.githubusercontent.com/7192835/40884312-6c39bb58-6754-11e8-94c5-2c18a08f41c0.png).

I have tried doing a complete install from scratch deleting all files in /opt/sourcetrail  /usr/bin/sourcetrail and .config/sourcetrail deleting the extracted file from the archive I downloaded and then reextracting it and installing with no change in behavior.

I will try taking it back to one screen and try sourcetrail again.

**Comment by DaveC49** [comment]
Going back to a single display, restarting Sourcetrail and reloading the project produces no change. I cant find any other files that source trail creates. I have previously used cscope to index the files but it does not mark the files.

**Comment by DaveC49** [comment]
If I delete the project files for the tictactoe project, but not the directory, it seems to automatically reindex it when I select it at startup and recreates the project files. If I do this with my own project, the indexer fails to start. The project I am trying to index is an open source GnuCash accounting program which has a mixture of C and C++ sources. I will try creating a simpler project to see if that works.

**Comment by mlangkabel** [comment]
Ok, maybe this is a stupid question but: Did you try to restart your computer after the Sourcetrail indexing stopped working?

**Comment by DaveC49** [comment]
I had previously rebooted but just did it again and the indexer dialog is now coming up again and working  It's unusual for Linux to require a reboot to fix things but there is always a first time.  Thanks for all the help

David
