### ISSUE TITLE
Indexing starts, but no indexing is happening. Gets stuck.

### ISSUE THREAD

**Issue by rnaby** [CoatiSoftware/SourcetrailBugTracker#591]
I've installed ***Sourcetrail_2018_2_36_Linux_64bit*** in my *Ubuntu 16.04 LTS* and it woks till creating project. Then it also starts indexing, but it gets stuck. Always ***0% Progress***. I tried with **tictactoe** project and ran indexing for 30 minutes. After 30 minutes it has shown ***0% Progress*** and ***0/7 Files***. Then I had a look in  the log file directory, located in ***Menu: Help -> Show Log Folder*** ( `~/.config/sourcetrail/logs`). But no logs has been generated.  

This tool is very handy. So, any kinda support will be very much appreciated. 

Thanks in advanced.

**Comment by egraether** [comment]
Did you try restarting you computer?
We have a known problem related to shared memory, which could be the reason for this.

**Comment by rnaby** [comment]
Yep... I did restart the software several times. Anyway, can you explain a little bit the ***shared memory*** issue, so I can test it in my machine? :smiley: @egraether

**Comment by egraether** [comment]
No, try restarting your computer

**Comment by rnaby** [comment]
Tried restarting my machine 5 times for 5 different projects. No luck. @egraether

**Comment by egraether** [comment]
Then try turning off **Multi-process indexing** in the preferences and also enable **File and Console logging**

**Comment by rnaby** [comment]
Tried... Still no luck... Also restarted the machine....No luck.

**Comment by egraether** [comment]
Did you enable **File and Console Logging**? Can you send me the log files please? support@sourcetrail.com

**Comment by rnaby** [comment]
No log file has been generated. :thinking:

**Comment by rnaby** [comment]
Restarted and tried with multiple project. No indexing as well as no log file. :thinking:

**Comment by egraether** [comment]
Is there already a `log` directory within `~/.config/sourcetrail`?
Does Sourcetrail have permission to create the `log` directory and add files inside?
Did you try to create a new project?
Was a `.srctrlprj` file created in the specified directory?
Is there a `.srctrldb` file in the same directory?

**Comment by rnaby** [comment]
Is there already a log directory within ~/.config/sourcetrail?
***YES***
Does Sourcetrail have permission to create the log directory and add files inside?
***YES***
Did you try to create a new project?
***YES***
Was a .srctrlprj file created in the specified directory?
***YES***
Is there a .srctrldb file in the same directory?
***YES***

**Comment by rnaby** [comment]
![screenshot-2018-06-07-12 43 18-001](https://user-images.githubusercontent.com/6243408/41082580-a68347a8-6a50-11e8-9ae6-0c0e46a4505f.png)

@egraether My project.

**Comment by egraether** [comment]
Maybe the problem is read permission then. Sourcetrail needs to access your c++ standard library. Does it have permission to read those files?

**Comment by egraether** [comment]
To prove that the problem is not related to permissions, it would be best to run `sudo sourcetrail` (although I can understand if you are hesitant in doing so). Did you try that already?

**Comment by rnaby** [comment]
Hey... Sorry for bothering you.
> Then try turning off Multi-process indexing in the preferences and also enable File and Console logging
I saved this configuration setting when `~/.config/sourcetrail` hadn't any write permission. SO the settings hasn't been saved. Now I saved the settings and it's working fine. 

Anyway, this tools is great. And thanks for the support.
