### ISSUE TITLE
for some files, the minimized icon does not work.

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#592]
I am now using Sourcetrail version 2018.2.36 64 bit on Centos.

I just noticed that after a search (eg, ??Something) I get a result of for example 77 references.
On the right side I can see all the files, each with the 3 icons on the right side (minimize, snippet and maximize).
I tried to open (click on snippet) all the files, and then minimize all files. 
The problem is that for a just a few files (maybe 5 out of 20?) the minimize button does not work.
When clicking on the minimize button, the file minimize itself but immediately goes back to snippet view.
In fact I can see the 'snippet' button flicker as-if it was clicked on (even though my mouse is still over the minimize button, and I clicked only once).
I do not see anything special with the files that cannot be minimized. Weird !

**Comment by egraether** [comment]
Thanks for reporting!
This issue was fixed with 2018.2.56
Please download the new 2018.2.77 release [here](https://www.sourcetrail.com/downloads).
