### ISSUE TITLE
Indexing Files stuck at 98%

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#593]
Sometimes, after a full re-indexing, the Indexing is stuck at 98%,
The indexing window shows 2463/2495 Files,
a filename. 
and 1578 Errors(122 Fatal)   <-- this is expected.
The line at the very bottom of the sourcetrail window shows
[2492/2495] Indexing file: a different filename.

After clicking Stop, the indexing window, shows Interrupting Indexing, Waiting for indexer threads to finish. Also stuck at this point.

After exiting sourcetrail, and restarting, it seems to say I need to restart indexing all files :-(

I am now using version 2018.2.77.
Note that I never had this problem with the previous version.

**Comment by pwillard2** [comment]
Forgot to mention I am using Centos.
Also forgot to mention that this (full) Indexing started witha project from a previous sourcetrail version, and sourcetrail mentioned re-indexing would be necessary.
Also when I restarted sourcetrail, I did not do another indexing, and sourcetrail seems to be stuck at
Preparing Project: Processing files

**Comment by pwillard2** [comment]
A second full indexing worked ! 
But this issue was painful as it takes 42 minutes to reindex all on my 12 core-cpu.
I am hoping it  won't happen again ;-)

**Comment by egraether** [comment]
Can you please enable "Console and File Logging" in your preferences and send the Log File located in `~/.config/sourcetrail/logs` to support@sourcetrail.com for a run where this occurs again.

Also, even after you close Sourcetrail while indexing, you should be able to browse the files that were indexed so far. I just tried and it seems that this is broken. I opened #594

**Comment by egraether** [comment]
New beta release is available and there where some related fixes. Can you please test if this issue is still present?
[download beta](https://www.sourcetrail.com/downloads#beta)

**Comment by egraether** [comment]
No update in 3 months, closing
(The issue that indexing had to be done from start after being stuck was fixed in a different issue)
