### ISSUE TITLE
Full indexing went from 40+ minutes to 20+ minutes just by selecting cross-compilation

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#595]
I created a kind of copy of existing source tree, and created a new SourceTrail project for it.
I was surprised to see how slow the full indexing was. More than 40+ minutes, instead of usual 20+ minutes. 
Looking at the project settings, I saw the new project did not have the cross-compilation selected. So I selected it (arch: arm, all other unknown) and bingo ! back to 20+ minutes.
Basically I don't care about cross-compile or not, I just want to browse the source code, and I do specify all relevant includes in the (Global) Include Paths settings.
Can you explain what's happening? Is sourcetrail looking in way too many directories?
It should be clearer what directories sourcetrail is looking into internally.
regards

**Comment by egraether** [comment]
We are using the LLVM/Clang compiler frontend for indexing, which generates an Abstract Syntax Tree that we travers to fetch all information.

We don't know why it's much faster if you specify cross-compilation, something must be handled differently in Clang's tokenizer or parser.

In case you want to look into it, we have a Sourcetrail project for [Clang 6.0.0 pre-indexed for download](https://www.sourcetrail.com/downloads#extra). You can start at [ClangTool](https://clang.llvm.org/doxygen/classclang_1_1tooling_1_1ClangTool.html). The indexed file and all compiler flag including cross-compilation is stored within [CompilationDatabase](https://clang.llvm.org/doxygen/classclang_1_1tooling_1_1CompilationDatabase.html), which is passed to ClangTool on construction.

**Comment by mlangkabel** [comment]
When the Clang tool is invoked Clang may add some more header search paths that depend on the cross compilation option that you choose for your project. So my guess is that choosing the "wrong" cross compilation option *and* adding the correct header search paths causes Clang to look into too many irrelevant header search paths what then causes the slowdown.

To inform the user about what's actually happening we could add a button to the "Empty C/C++" project setup modes that shows all derived indexing options.

**Comment by pwillard2** [comment]
Hello. 
I think it will be nice to be able to see ALL the options passed to Clang. If it's simpler, this can just be added to the log file (no UI).
I am still experimenting with different include/cross-compile options, and index time varies widely. For example, it could depend on number of fatal errors, or of includes not found...

**Comment by mlangkabel** [comment]
Implemented with Sourcetrail 2018.3.18. Now the whole Clang invocation is logged before indexing a source file, including all implicit and derived arguments.
