### ISSUE TITLE
Old nodes and edges sometimes stay in the graph

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#609]
They are not interactive and won't disappear.
Restart of Sourcetrail necessary.
No steps to reproduce so far.
via twitter: https://twitter.com/TTimo/status/1029775302128369664

**Comment by egraether** [comment]
No clue about the origin of the problem so far.
Added explicit graph clearing when going to `overview` with 2018.3.33 which should clear everything, so the user can continue without restarting.

**Comment by TTimo** [comment]
It happened again on latest, this time on Linux. I don't have a good way to reproduce, but it seems to happen when I type a symbol in the top search bar, use the arrows to select the auto complete result and hit enter.

**Comment by egraether** [comment]
I did not experience this issue after our 2018.3.55 release. Is it gone?

**Comment by TTimo** [comment]
Feel free to close, I can re-open if needed. I have not used the new builds enough to know.
