### ISSUE TITLE
Wrong way to access LocalAppData

### ISSUE THREAD

**Issue by ibookstein** [CoatiSoftware/SourcetrailBugTracker#612]
Application crashes with win32 exception at startup. Accesses `Roaming/../Local`, thereby assuming they are adjacent on the filesystem. For me, they are not. 
Attempts to perform file copy operation for `ApplicationSettings.xml` from installation directory and fails because target directory doesn't exist. Exception is thrown and the process dies.
The fact that no information is displayed about the error and the application simply crashes ungracefully with an **uncaught** exception is a separate bug in itself, I had to do some WinDBG-and-Procmon-fu to determine the cause of the exception.

**Comment by egraether** [comment]
Thanks for reporting, we will look into it!

**Comment by mlangkabel** [comment]
Fixed with Sourcetrail 2018.3.31
