### ISSUE TITLE
Source files with .C not indexed.

### ISSUE THREAD

**Issue by janagulo** [CoatiSoftware/SourcetrailBugTracker#614]
Even though the software allows one to add extra extensions manually, which true for above case(see below), source files with the extension(.C) -- note the case, are ignored and thus not indexed.
<source_extensions>
                <source_extension>.cpp</source_extension>
                <source_extension>.cxx</source_extension>
                <source_extension>.cc</source_extension>
                **<source_extension>.C</source_extension>**
            </source_extensions>

**Comment by egraether** [comment]
Fixed with 2018.3.36
The casing is usually ignored, bu this got broken. The other direction still works, so as workaround you can define the extension lowercase `.c` and then `.C` file will also get indexed.
