### ISSUE TITLE
Multi level call edges in call graph don't change when moving nodes

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#639]
<img width="531" alt="screenshot 2018-12-04 at 17 05 51" src="https://user-images.githubusercontent.com/201867/49455105-e0bfb900-f7e6-11e8-8a39-bb7080022dce.png">

**Comment by TomSmartBishop** [comment]
Came across that as well :(

**Comment by egraether** [comment]
Fixed with 2018.4.54

Virtual nodes in depth graph edges are now removed as soon as either end of the edge is moved. In some cases this can cause a more messy layout.
