### ISSUE TITLE
Sourcetrail was unable to locate Java on this machine.

### ISSUE THREAD

**Issue by egoarka** [CoatiSoftware/SourcetrailBugTracker#644]
After creating the new project this message pops up
```
Sourcetrail was unable to locate Java on this machine.
Please make sure to provide the correct Java Path in the preferences.

Error: Cannot load symbol 'JNI_CreateJavaVM' from library '/usr/bin/java': dlsym(0x60000058e940, JNI_CreateJavaVM): symbol not found
```

`Darwin name.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

**Comment by mlangkabel** [comment]
Hi @egoarka, thanks for reaching out. Can you please tell us the exact string that the Sourcetrail preferences display for the "Java Path" setting?

**Comment by egoarka** [comment]
of course
![image](https://user-images.githubusercontent.com/29709538/49756926-2ccd9a80-fccc-11e8-83e4-34a7be1380e4.png)

ps
`/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home`
`$ ls -a | pbcopy`
```
.
..
README.html
bin
conf
include
jmods
legal
lib
release
```

**Comment by egoarka** [comment]
Ah.. I get things work
is there a mistake in docs or mine?
in docs it says find jre lib in there

`/Library/Java/JavaVirtualMachines/<jdk_version>/Contents/Home/jre/lib/jli/libjvm.dylib`

but I found mine here
`/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib`

**Comment by mlangkabel** [comment]
Thanks for letting us know!

**Comment by egoarka** [comment]
@egraether https://sdkman.io/sdks#java
