### ISSUE TITLE
[Feature request] Analyse pipeline of computation

### ISSUE THREAD

**Issue by egoarka** [CoatiSoftware/SourcetrailBugTracker#645]
Would be cool if it could support analyze on some pipeline of computation (make decisions or suggestions what these two methods calling each other possibly do or some method composed together (like monads or this stuff))

(all these mentioned are examples)

**Comment by egraether** [comment]
Can you provide some sample code for this suggestions please? What do you want to see that Sourcetrail does not currently show?

**Comment by egoarka** [comment]
@egraether ah, it's hard to fully convey the idea, but I will try

lets imagine you have this function in your code: f(x) = x ^ 2
and you want to get more information about it (how it behaves: from the plot or its properties), we can apply some range of inputs (predefined, clearly it's a range of numbers) on this function and try to gather information and plot it on display
in the best way, if SourceTrail could itself define (at least raw or gather from unit tests or define inputs yourself) ranges make decisions and suggestions
(this is the only example, of course, exploring function returning numbers easier to plot than a function returning map<string, map<watever, watever>>) but this idea can be started from small steps 
any way... that's it

**Comment by egraether** [comment]
Thanks for the explanation!
I'm afraid this is going heavily into dynamic analysis during runtime, which we don't plan on doing in the near or far future for multiple reasons. This feature suggestion would be a better fit for debugger vendors I'm afraid.
