### ISSUE TITLE
Functions with a lot of template parameters might fill whole screen

### ISSUE THREAD

**Issue by TomSmartBishop** [CoatiSoftware/SourcetrailBugTracker#652]
I have some function calls with multiple template parameters that fill the whole screen. It would be better to use multiple lines or just '...' after some max len:

![too_long](https://user-images.githubusercontent.com/1806315/50219570-93674e00-0387-11e9-9cc3-1411a2e49ff1.png)

**Comment by egraether** [comment]
So far we use `...` for node names longer than 50 characters that are inactive. But as soon as a node gets activated we show the whole name.

I still think it makes sense to show more of the name for active nodes, but maybe we should start using `...` after 100 characters. The tooltip will still show the whole name.

What do you think?

**Comment by TomSmartBishop** [comment]
Sounds reasonable and certainly good enough for me. You can maybe consider a small arrow button (>) at the end to expand on demand (similar to the classes).

**Comment by egraether** [comment]
Fixed with 2018.4.49

I decided to elide with `...` after 100 characters for active node names. No arrow button to expand for now. Tooltip shows the whole name. We will see if users have complaints about that.
