### ISSUE TITLE
Feature Request: Pin classes

### ISSUE THREAD

**Issue by TomSmartBishop** [CoatiSoftware/SourcetrailBugTracker#655]
Sometime I just want to keep drilling, unfortunately at some point the layout collapses everything - after 3 hops? I understand that it is maybe impossible to make a clean layout but it would be great to pin some classes that shouldn't go away.

**Comment by egraether** [comment]
I agree. This has been on our list for quite a while. I hope I get around to do it soon.
Duplicate of #50, closing
