### ISSUE TITLE
FATAL error "cstddef" file not found

### ISSUE THREAD

**Issue by acgetchell** [CoatiSoftware/SourcetrailBugTracker#664]
## Description
I get a fatal indexing error of "cstddef" file not found from line 18 of `/usr/local/Cellar/boost/1.68.0_1/include/boost/config/detail/select_stdlib_config.hpp`.

## Steps to reproduce
Index my project https://github.com/acgetchell/CDT-plusplus

## OS Version
macOS 10.14.3

## Sourcetrail version
2018.4.45 64-bit Database Version 23

## Screenshot
![screen shot 2019-01-27 at 8 42 17 am](https://user-images.githubusercontent.com/434849/51803935-8273ed00-220f-11e9-9a56-10be257f2720.png)

## Log Files

None in `~/Library/Application Support/Sourcetrail/log`

**Comment by egraether** [comment]
This means there is a problem with your Global Include Paths. We made some fixes in our upcoming release to avoid issues like this. Can you please install our [Sourcetrail 2019.1.0 beta](https://www.sourcetrail.com/downloads#beta) and test again?

**Comment by acgetchell** [comment]
- `brew cask uninstall sourcetrail`
- `brew cleanup`
- installed 2019.1.0 beta
- regenerated compile_commands.json
- setup a new project

Same results.

![screen shot 2019-01-27 at 12 01 44 pm](https://user-images.githubusercontent.com/434849/51806189-ae9d6700-222b-11e9-9811-44e9ce683aff.png)

**Comment by egraether** [comment]
Thanks for testing!
Can you please open your Sourcetrail preferences and provide a screenshot of your **Global Include Paths**?
Do you get a warning after clicking `save` in the preferences window?

**Comment by acgetchell** [comment]
`Detect` fixed the issue!

Thanks!
