### ISSUE TITLE
Add dashed inheritance edge to graph legend

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#688]

**Comment by egraether** [comment]
implemented with 2019.1.31

**Comment by GitGoogol** [comment]
Where can I download this version? My license is valid till 2019.1 but I just can get 2019.1.11.

**Comment by egraether** [comment]
This fix is only available in our [2019.2.39 release](https://www.sourcetrail.com/downloads).

Your confusion is caused by a problem in our versioning procedure. So far we only increased the version number as soon as we released the beta of the new release. Therefore a lot of fixes still show the previous version number here on our bug tracker.

From now on we increase the version number right when we start working on the new release, so this problem will be avoided.
