### ISSUE TITLE
Windows 10 uses Qt fallback UI for rendering standard UI elements

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#703]
e.g checkboxes and dropdown lists in preferences look old

**Comment by mlangkabel** [comment]
Just came across this thread which may help: https://forum.qt.io/topic/91750/why-a-gui-looks-different-on-different-windows-versions/9

**Comment by mlangkabel** [comment]
fixed with Sourcetrail 2019.3.25
