### ISSUE TITLE
[Feature] Detect changed files and silently update the database

### ISSUE THREAD

**Issue by pidgeon777** [CoatiSoftware/SourcetrailBugTracker#706]
It would be great to have an option so that, when one or more indexed files changes, then Sourcetrail automatically detect it and update the database accordingly (as if doing Edit -> Refresh -> Updated files manually).

**Comment by egraether** [comment]
Duplicate of #313 -> Closing

We had that feature in an early beta version. In reality it is a bit annoying, since indexing takes a couple seconds as least, you constantly keep the CPU busy and how do you deal with a half implemented feature that throws errors?
