### ISSUE TITLE
Passing a string #define via command line fails

### ISSUE THREAD

**Issue by mauline** [CoatiSoftware/SourcetrailBugTracker#738]
I'm not able to pass a string as a #define via the -D command line switch to the compiler. Maybe it's not documented or I haven't been able to find it in the docs?

Given this C code:
```
#include <stdio.h>
#include <stdlib.h>
int main(void)
{
    printf("%s\n", HELLO " world");
    return EXIT_SUCCESS;
}
```

I can compile it on the command line using

```
gcc -O2 -Wall -DHELLO='"Hello"' -o main main.c
```

But passing the same -D command line switch in the GUI fails, as do several combinations using the backslash.

Any hints?

**Comment by mauline** [comment]
Sourcetrail version is 2019.3.46, platform is Ubuntu 18.04.

**Comment by egraether** [comment]
Works for me  in the GUI when defined with double quotes: `-DHELLO="Hello"`.
(Every flag needs a separate line)

**Comment by mauline** [comment]
You are right, thank you! I was assuming that the same syntax as on the command line applies and was trying every possible way to escape the quotes :)
