### ISSUE TITLE
Compilable source shows indexing errors

### ISSUE THREAD

**Issue by mauline** [CoatiSoftware/SourcetrailBugTracker#739]
Sorry for coming up with another issue.

Given this source file:

```
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
int main(void)
{
    printf("PATH_MAX=%d\n", PATH_MAX);
    printf("FILENAME_MAX=%d\n", FILENAME_MAX);
    return EXIT_SUCCESS;
}
```

which compiles cleanly using either of

```
gcc -O2 -Wall -o main main.c
clang-7 -O2 -Wall -o main main.c
```

I get an error in Sourcetrail when indexing: use of undeclared identifier "PATH_MAX"

Sourcetrail 2019.3.46 - 64 bit on Ubuntu 18.04

**Comment by egraether** [comment]
Works fine for me. Do you get any errors regarding missing files?

**Comment by mauline** [comment]
No, this is the only error I get.

**Comment by egraether** [comment]
Well, thanks for reporting! You should see the error messages of all errors in the status view that appears at the bottom of the window. If it doesn't appear you need to click on `errors` in the bottom right of the status bar at the bottom of the window. What errors do you get?

**Comment by mauline** [comment]
I get exactly one error as noted above: use of undeclared identifier "PATH_MAX"

I've investigated the problem a bit further using the sourcetrail log. This is the clang command line from the log:

```
"clang-tool" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" \
    "-disable-free" "-disable-llvm-verifier" "-discard-value-names" \
    "-main-file-name" "main.c" "-mrelocation-model" "static" "-mthread-model" \
    "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" \
    "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" \
    "x86-64" "-dwarf-column-info" "-debugger-tuning=gdb" "-resource-dir" \
    "lib/clang/8.0.0" "-isystem" "/home/mauline/src/tmp" "-isystem" \
    "/usr/include/c++/7" "-isystem" "/usr/include/x86_64-linux-gnu/c++/7" \
    "-isystem" "/usr/include/c++/7/backward" "-isystem" "/usr/local/include" \
    "-isystem" "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed" "-isystem" \
    "/usr/include/x86_64-linux-gnu" "-isystem" "/usr/include" "-isystem" \
    "/opt/sourcetrail/data/cxx/include" "-internal-isystem" "/usr/local/include" \
    "-internal-isystem" "lib/clang/8.0.0/include" "-internal-externc-isystem" \
    "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" \
    "-internal-externc-isystem" "/usr/include" "-w" "-std=c11" \
    "-fdebug-compilation-dir" "/home/mauline/src/tmp" "-ferror-limit" "0" \
    "-fmessage-length" "0" "-fobjc-runtime=gcc" "-fexceptions" \
    "-fdiagnostics-show-option" "-x" "c" "/home/mauline/src/tmp/main.c" "-faddrsig"
```

After replacing "clang-tool" with "clang-7" I get the exact same error:

```
/home/mauline/src/tmp/main.c:6:29: error: use of undeclared identifier 'PATH_MAX'
    printf("PATH_MAX=%d\n", PATH_MAX);
                            ^
1 error generated.
```

Looks like any of the command line switches causes this behavior because as said above, using straight clang-7 it compiles fine.

**Comment by mauline** [comment]
Ok, found it. -std=c11 is the culprit. It causes pure C11 mode and disables anything not conforming. This is the reason why FILENAME_MAX (which is ISO C) is known, but PATHNAME_MAX (POSIX) is not.

I should have chosen gnuc11 as C Standard in the profile instead of c11 - my fault. But still somewhat strange. PATHNAME_MAX is POSIX and not GNU. 

Anyway, thanks a lot for helping! I'm trying to get into sourcetrail but it doesn't seem to be as easy as it looks.
