### ISSUE TITLE
What technologies were used/are used to make this app?

### ISSUE THREAD

**Issue by cata0309** [CoatiSoftware/SourcetrailBugTracker#745]
Hello ! I am using GNU/Linux and I really like how responsive and clean is the UI. What technologies did you use to make the app (frontend, backend,etc)? I saw something similar at another app(GitAhead) but I still couldn't figure it out. I am asking for my future projects.

**Comment by egraether** [comment]
We use Qt and customize a lot with stylesheets, that's pretty much it.
