### ISSUE TITLE
Search only in specific node types like files or classes

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#78]
Add filter syntax to search bar which allows for only searching within files, classes, etc.

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Comment from duplicate issue #339
> Something like :enum foo - would find all enums which contain foo . :record foo woudl find all structs and classes which match foo.

**Comment by egraether** [comment]
+1 by [reddit](https://www.reddit.com/r/cpp/comments/6bnkr7/sourcetrail_012_instantly_generate_call_and/dhrjuib/)

**Comment by egraether** [comment]
+1 by mail
e.g. use modifier strings: @class, @method, @function

**Comment by deepankarsharma** [comment]
Can we raise the priority for this? Lack of usable search means I dont use SourceTrail inspite of paying for it.

**Comment by egraether** [comment]
Yes, it's in high demand and shouldn't be too hard to add. I think I can make it work.

**Comment by deepankarsharma** [comment]
How about generalizing this to an API/SDK to interact with the underlying graph. If the following two APIs existed then the tool would be very useful for me

a. Visitation API for the graph for a given project. User can subclass some visitor and override things like visit_function, visit_struct, visit_file, visit_namespace etc. API would be applied top down. Ie if an overridden visit_file returns false for a given filename then nothing from that file would be visited.
b. Ability to contribute QWidget based views to the GUI

**Comment by egraether** [comment]
Implemented with 2017.3.32

There are filter keywords for symbol types within the search autocompletion list now. E.g. selecting `class` will add this filter to the search bar and search results will only show classes. Filters can also get combined, e.g. to search within all `function` and `method` symbols.

I'm closing this issue now, but opened other issues for the additional suggestions:
#460 for Visitation feature request.
#461 for UI-Plugin feature request.

**Comment by egraether** [comment]
Now available in release [2017.3.48](https://www.sourcetrail.com/downloads)

**Comment by deepankarsharma** [comment]
Is there some way to enter into filter mode purely by typing text? I can pick filter from dropdown but things of form class: foo dont work.

**Comment by egraether** [comment]
* type `cla`
* press `tab` to autocomplete to `class:`
* type `foo`

You will only see classes containing the letters `foo` now.
