### ISSUE TITLE
On-screen searching in graph and code view

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#79]
by just starting to type, pressing cmd-f, or maybe by using /, similar to searching in vim/less/… on unix

**Comment by payload** [comment]
Isn't this the case already with Ctrl + F ?

**Comment by egraether** [comment]
@payload No, this feature should work like 'Ctrl + F' in a web browser. It should only search in the currently visible contents on the screen. That way you can quickly find any piece of text in the currently visible file or graph.

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
+1 by mail

**Comment by egraether** [comment]
Implemented with 2017.3.61

Currently it works like this:

* Use menu action `Edit -> Find in View` or `Ctrl + D` to display search bar at bottom of the main window. (`Ctrl + D` was used for creating bookmarks so far, which is now `Ctrl + S`)
* All node names in the graph window and displayed source code in the code window will be searched. There are check-boxes for removing the results for either view.
* Use `Return` or the buttons `<` and `>` to iterate through matches. Graph and Code window will scroll to the currently active match. Graph window results are always iterated first.
* Use `ESC` or the `x` button within the bar to close

**Comment by egraether** [comment]
Also open screen search when pressing `/` or `?` similar to vim.
